Aurora login now complains if instance is not running or not found.
Ticket: [INFRA-770]
Change-Id: I8dbdb678df543fd9e9ca2e33dccc2a1affcab352
Signed-off-by: Ali Rizwan <alir@plumgrid.com>

diff --git a/aurora/aurora_utils.sh.in b/aurora/aurora_utils.sh.in
--- a/aurora/aurora_utils.sh.in
+++ b/aurora/aurora_utils.sh.in
@@ -275,14 +275,15 @@ function login_instance() {
     exit 1
   fi
   local INSTANCE_NAME="${emailid}-$1"
-  gcloud compute instances list ${INSTANCE_NAME} | grep "${INSTANCE_NAME}" || RESULT=$? &> /dev/null
-  local INSTANCE_IP=$(get_instance_ip ${INSTANCE_NAME})
-  if [[ $RESULT -ne 0 ]];then
-    echo "INSTANCE ${INSTANCE_NAME} does not exist"
-    show_login_help
+  local retval=$?
+  gcloud compute instances list ${INSTANCE_NAME} | grep "${INSTANCE_NAME}" | grep "RUNNING" || retval=$?
+  if [[ $retval -eq 0 ]]; then
+    local INSTANCE_IP=$(get_instance_ip ${INSTANCE_NAME})
+    run_cmd_gci_sshforwarding ${INSTANCE_IP} "/bin/bash"
+  else
+    echo "Instance not found or not running."
     exit 1
   fi
-  run_cmd_gci_sshforwarding ${INSTANCE_IP} "/bin/bash"
 }
 # *****************************************************************************
 # Function: list_entities
