Added aurora test functionality.
Added local changes functionality. Can be used by "aurora custom_tests"
Options are now parsed in the their respective functions instead of aurora.sh
Merged run_aurora_build and run_aurora_run functionality into aurora_build/run
Changed interfaces for aurora util functions.
Added help for custom_tests

Patch 12:
changed custom_tests to debug-test
Reworked help
Check for ALPS_PATH being valid
Removed branch option from debug-test

Ticket: [INFRA-655]
Change-Id: Icffdc0c1d26a9a2479730af14ea83a8b03aa6bb5
Signed-off-by: Ali Rizwan <alir@plumgrid.com>

diff --git a/aurora/aurora_build.sh.in b/aurora/aurora_build.sh.in
--- a/aurora/aurora_build.sh.in
+++ b/aurora/aurora_build.sh.in
@@ -1,4 +1,5 @@
 #!/bin/bash -e
+source help.sh
 
 export PATH=@CMAKE_BINARY_DIR@/:/opt/pg/scripts:$PATH
 echo "aurora_build.sh started with [aurora_build.sh  $@]"
@@ -7,64 +8,96 @@ echo "aurora_build.sh started with [aurora_build.sh  $@]"
 source aurora_infra_settings.conf
 source /home/$USER/.aurora.conf
 
-# TODO: SN_ID variable should hold the "v3-d1" part as well.
-# This way we will not need to change v3 manually.
-SN_ID=$(get_latest_snapshot_id)
-SNAP1=${PRIM_INST_NAME}-d1-${SN_ID}
-SNAP2=${PRIM_INST_NAME}-d2-${SN_ID}
-DOCK_NAME=pg-docker-repo:5000/pg_dev:${SN_ID}
 
+#Show help
+if [[ $1 == "help" ]]; then
+  show_build_help
+  exit 1
+fi
 # TODO: Make a decision about machine type and Disk sizes.
 
 BRANCH=""
-REFSPEC=""
+REFSPEC="none"
+TAG="none"
 PROJECT=""
 
 declare -A MINOR_STEPS_ST
 declare -A MINOR_STEPS_ED
 MAJOR_STEPS="build"
-MINOR_STEPS_ST[init]=1
 MINOR_STEPS_ST[build]=1
-MINOR_STEPS_ED[init]=1
-MINOR_STEPS_ED[build]=17
+MINOR_STEPS_ED[build]=20
 
+CONTINUE=0
 
-function usage() {
-cat <<EOF
-usage: $0
- -c | --cleanup : Test Cleanup
- -Q | --major : Jump to specific major step in the install process
- -R | --minor_st : Jump to specific minor step in the install process
- -E | --minor_end : Stop at this step when in debug
- -G | --gerrit_refpec: Mention the gerrit refspec
- -B | --branch: branch to run the setup on. Options: master, stable_4_0
- -P | --project: project on which the code change is expected. Options: alps, pg_ui, etc
- -O | --stop : DONT Continue beyond the specifict step to end of the installation
- -h | --help : help
-EOF
-exit 0
-}
-
-# Parsing arguments
-while [[ $# -gt 0 ]]; do
+# read the options
+TEMP=`getopt -o Kr:t:Cb:p:Q:R:E:Oh --long keep-running,refspec,tag:,\continue,branch:,proj:,stop,help,major:,minor_st:,minor_end: -n 'aurora.sh' -- "$@"`
+eval set -- "$TEMP"
+while true ; do
   case "$1" in
-     -c| --cleanup ) CLEANUP=1;  ;;
-     -Q| --major ) MAJOR_STEPS="$2"; TMP_MAJOR="$2"; shift ;;
-     -R| --minor_st ) MINOR_STEPS_ST[$TMP_MAJOR]="$2"; shift ;;
-     -E| --minor_end ) MINOR_STEPS_ED[$TMP_MAJOR]="$2"; shift ;;
-     -G| --gerrit_refspec ) REFSPEC=$2; shift ;;
-     -B| --branch ) BRANCH=$2; shift ;;
-     -P| --project ) PROJECT=$2; shift ;;
-     -I| --instance_name ) INSTANCE_NAME=$2; shift ;;
-     -O| --stop ) STOP=1; ;;
-     -h | --help ) usage; ;;
-    -- ) shift; break ;;
-    * )
-      echo "Unknown parameter: $1";
-      usage; break;;
+     -K| --keep-running ) KEEP_RUNNING=1; shift ;;
+     -r| --refspec) REFSPEC=$2; shift 2 ;;
+     -t| --tag) TAG=$2 ; shift 2 ;;
+     -C| --continue) CONTINUE=1 ; shift ;;
+     -b|--branch) BRANCH=$2; shift 2 ;;
+     -p|--proj) PROJECT=$2; shift 2 ;;
+
+     -Q| --major ) MAJOR_STEPS="$2"; TMP_MAJOR="$2"; shift 2;;
+     -R| --minor_st ) MINOR_STEPS_ST[$TMP_MAJOR]="$2"; shift 2 ;;
+     -E| --minor_end ) MINOR_STEPS_ED[$TMP_MAJOR]="$2"; shift 2 ;;
+     -O| --stop ) STOP=1; shift ;;
+     -h| --help ) show_build_help; exit 0; shift;;
+     --) shift ; break ;;
+     *) exit 1 ;;
   esac
-  shift
 done
+
+#Check required Arguments
+if [[ -z "$BRANCH" || -z "PROJECT" ]]; then
+  echo "Required argument -b(--branch) or -p(--project)"
+  show_build_help
+  exit 1
+fi
+
+#keep_running equalling 1 means -k was specified, end step should be 1 less.
+if [[ $KEEP_RUNNING == "1" ]]; then
+  END_STEP=19
+fi
+#Generating Instance name piece by piece
+INSTANCE_NAME=${gerritid_lower}
+#Append tag if provided
+if [[ $TAG != "none" ]]; then
+  #Only keeping alphanumeric characters
+  TAG=${TAG//[^[:alnum:]]/}
+  #Converting to lowercase since instance name cannot contain uppercase characters
+  TAG=${TAG,,}
+  INSTANCE_NAME=${INSTANCE_NAME}-${TAG}
+fi
+
+#Append refspec
+if [[ $REFSPEC == "none" ]]; then
+  MOD_BRANCH=$(echo "$BRANCH" | tr _ -)
+  INSTANCE_NAME=${INSTANCE_NAME}-bld-${MOD_BRANCH}
+else
+  MOD_REFSPEC=$(echo "$REFSPEC" | sed -e 's/refs\/changes\///')
+  MOD_REFSPEC=$(echo "$MOD_REFSPEC" | tr /_ -)
+  INSTANCE_NAME=${INSTANCE_NAME}-bld-${MOD_REFSPEC}
+fi
+
+step_rec_file=$WORKSPACE/logs/${INSTANCE_NAME}-last-successful-step
+#Validate Inputs
+check_build_inputs $INSTANCE_NAME $PROJECT $REFSPEC $BRANCH
+#Check /home/$USER/.ssh/id_rsa.pub file
+check_file_existence "/home/$USER/.ssh/id_rsa.pub"
+# If "continue" switch has been given then do following steps
+#   a. Get the last successfully completed step.
+#   b. Start the build process from step next to last completed step.
+if [[ $CONTINUE == "1" ]] ; then
+  # Get the last successfull step from /tmp/${INSTANCE_NAME}-last-successful-step
+  LAST_SUCCESSFULL_STEP=( $(<${step_rec_file}) )
+  START_STEP=$((LAST_SUCCESSFULL_STEP+1))
+else
+  check_instance_limit
+fi
 
 # Describe the possible mappings for branch->component translations
 declare -A branch_to_component
@@ -81,12 +114,12 @@ step_file=$WORKSPACE/logs/${INSTANCE_NAME}-last-successful-step
 #Get the IP address of the instances, needed incase continue is specified.
 INSTANCE_IP=$(get_instance_ip ${INSTANCE_NAME})
 
-function init_id() {
-  conf_file="/opt/pg/scripts/aurora.conf"
-  echo "Please enter your gerrit id: "
-  read gerritid
-  echo "gerritid=${gerritid}" > ${conf_file}
-}
+# TODO: SN_ID variable should hold the "v3-d1" part as well.
+# This way we will not need to change v3 manually.
+SN_ID=$(get_latest_snapshot_id)
+SNAP1=${PRIM_INST_NAME}-d1-${SN_ID}
+SNAP2=${PRIM_INST_NAME}-d2-${SN_ID}
+DOCK_NAME=pg-docker-repo:5000/pg_dev:${SN_ID}
 
 function build_image() {
   local step=$1
@@ -227,33 +260,19 @@ function build_image() {
     ;;
 
   17)
-    local local_file=$(mktemp /tmp/post_build_all.sh-XXXXX)
-    cat /dev/null > ${local_file}
-    echo "find /home/plumgrid -name \"*.o\" -not -name 'setcontext.o' | xargs rm -f" >> ${local_file}
-    echo "find /home/plumgrid -name \"*.a\" | xargs rm -f" >> ${local_file}
-    echo "find /home/plumgrid -name \"*_pre\" | xargs rm -f" >> ${local_file}
-    echo "#sudo su plumgrid -c /bin/bash" >> ${local_file}
-
-    tryexec upload_to_docker ${INSTANCE_IP}  ${local_file} ${local_file}
-    rm ${local_file}
-    tryexec run_cmd_docker ${INSTANCE_IP} "/bin/bash ${local_file}"
-    record_step $step $step_file
-    ;;
-
-  18)
     echo "Making a snapshot for the container"
     tryexec run_cmd_gci ${INSTANCE_IP} "echo \"pg_dev_${INSTANCE_NAME}\" > docker_build_id" "t"
     tryexec run_cmd_gci ${INSTANCE_IP} "sudo docker commit \`cat ./local_docker_id\` pg_dev_${INSTANCE_NAME}:latest"
     record_step $step $step_file
     ;;
 
-  19)
+  18)
     echo "Making sure docker(pg_dev_${INSTANCE_NAME}:latest) is commited successfully"
     tryexec verify_docker_commited ${INSTANCE_IP} "pg_dev_${INSTANCE_NAME}"
     record_step $step $step_file
     ;;
 
-  20)
+  19)
     BUILD_ID=`echo ${INSTANCE_NAME} | sed "s/${gerritid_lower}-//"`
     echo "Creating a snapshot of VM for BUILD-ID=${BUILD_ID}"
     tryexec run_cmd_gci ${INSTANCE_IP} "echo ${INSTANCE_NAME}-ssd1 > ~/build_d1_snapshot"
@@ -275,7 +294,7 @@ function build_image() {
     record_step $step $step_file
     ;;
 
-  21)
+  20)
     echo "Shutting down the Instance ${INSTANCE_NAME}"
     exec_gcloud_cmd instances delete ${INSTANCE_NAME} --delete-disks all  -q
     rm $step_file
@@ -297,10 +316,6 @@ for MAJOR_STEP in $MAJOR_STEPS; do
     echo "    === Starting STEP [$MAJOR_STEP][$MINOR_STEP] ==="
     echo ""
     case "$MAJOR_STEP" in
-      init)
-        echo "Going to call init function"
-        init_id
-      ;;
       build)
         start_time=$(date +%s)
         build_image $MINOR_STEP
diff --git a/aurora/aurora_run.sh.in b/aurora/aurora_run.sh.in
--- a/aurora/aurora_run.sh.in
+++ b/aurora/aurora_run.sh.in
@@ -1,4 +1,5 @@
 #!/bin/bash -e
+source help.sh
 
 echo "aurora_run.sh started with [aurora_run.sh  $@]"
 
@@ -8,59 +9,96 @@ export PATH=@CMAKE_BINARY_DIR@/:/opt/pg/scripts:$PATH
 source /home/$USER/.aurora.conf
 source aurora_infra_settings.conf
 
-
-declare -A MINOR_STEPS_ST
-declare -A MINOR_STEPS_ED
-MAJOR_STEPS="build"
-MINOR_STEPS_ST[run]=1
-MINOR_STEPS_ED[run]=15
-
-function usage() {
-cat <<EOF
-usage: $0
--c | --cleanup : Test Cleanup
--Q | --major : Jump to specific major step in the install process
--R | --minor : Jump to specific minor step in the install process
--E | --minor_end : Stop at this step when in debug
--B | --build_id: Mention the build-id on which you want to test
--T | --test: Test script to run.
--o | --log_dir: Directory where you want to download the logs of this run.
-                Please provide absolute path.
--U | --test_uuid: Test unique id to use.
--O | --stop : DONT Continue beyond the specifict step to end of the installation
--h | --help : help
-EOF
-exit 0
-}
-
-# Parsing arguments
-while [[ $# -gt 0 ]]; do
-  case "$1" in
-    -c|--cleanup ) CLEANUP=1;  ;;
-    -Q| --major ) MAJOR_STEPS="$2"; TMP_MAJOR="$2"; shift ;;
-    -R| --minor ) MINOR_STEPS_ST[$TMP_MAJOR]="$2"; shift ;;
-    -E| --minor ) MINOR_STEPS_ED[$TMP_MAJOR]="$2"; shift ;;
-    -B| --build_id ) BUILD_ID=$2; shift ;;
-    -T| --test_script ) TEST_SCRIPT=$2; shift ;;
-    -I| --instance_name ) INSTANCE_NAME=$2; shift ;;
-    -o| --log_dir) LOG_DIR=$2; shift ;;
-    -U| --test_uuid ) SUUID=$2; shift ;;
-    -O| --stop ) STOP=1; ;;
-    -h| --help ) usage; ;;
-    --skip-automaton-init ) SKIP_AUTOMATON_INIT="$2"; shift ;;
-    -- ) shift; break ;;
-    * )
-      echo "Unknown parameter: $1";
-      usage; break;;
-  esac
-  shift
-done
-
-printf "\n\n********* RUNID= ${SUUID} *********\n\n"
-if [ -z ${SUUID+x} ]; then
-  echo "Input parameter -U is required"
+#Show help
+if [[ $1 == "help" ]]; then
+  show_run_help
   exit 1
 fi
+#Starting and ending steps
+declare -A MINOR_STEPS_ST
+declare -A MINOR_STEPS_ED
+MAJOR_STEPS="run"
+MINOR_STEPS_ST[$MAJOR_STEPS]=1
+MINOR_STEPS_ED[$MAJOR_STEPS]=15
+
+UUID=`uuidgen`
+SUUID_="${UUID##*-}"
+SUUID="${SUUID_,,}"
+
+#Set default values for optional arguments
+LOG_DIR="${WORKSPACE}/logs/"
+SKIP_AUTOMATON_INIT=0
+CONTINUE=0
+KEEP_RUNNING=0
+LOCAL_CHANGES=0
+
+
+# read the options
+TEMP=`getopt -o l:s:o:n:W:CSKhLc:a:R:E: --long buildid:,script:,log_dir:,runid:,WORKSPACE:,\continue,skip-automaton,keep-running,\help,\local-changes,commit:,alps-path:,minor_st:,minor_end: -n 'aurora.sh' -- "$@"`
+eval set -- "$TEMP"
+while true ; do
+  case "$1" in
+#Basic Funtionality
+    -l| --buildid ) BUILD_ID=$2; shift 2 ;;
+    -s| --script ) TEST_SCRIPT=$2; shift 2 ;;
+    -o| --log_dir) LOG_DIR=$2; shift 2 ;;
+    -n| --runid ) RUNID=$2 ; shift 2 ;;
+    -W| --WORKSPACE) export WORKSPACE=$2 ; shift 2 ;;
+    -C| --continue ) CONTINUE=1; shift ;;
+    -S| --skip-automaton ) SKIP_AUTOMATON_INIT=1; shift ;;
+    -K| --keep-running ) KEEP_RUNNING=1; shift ;;
+    -h| --help ) show_run_help;exit 0; shift ;;
+#Local changes flags
+    -L| --local-changes) LOCAL_CHANGES=1; shift ;;
+    -c| --commit) COMMIT_ID=$2; shift 2;;
+    -a| --alps-path) ALPS_PATH=$2; shift 2;;
+#Start-End steps
+    -R| --minor_st ) MINOR_STEPS_ST[$MAJOR_STEPS]="$2"; shift 2 ;;
+    -E| --minor_end ) MINOR_STEPS_ED[$MAJOR_STEPS]="$2"; shift 2 ;;
+    --) shift ; break ;;
+    *) exit 1 ;;
+  esac
+done
+#Check required Arguments
+if [[ -z "$BUILD_ID" || -z "$TEST_SCRIPT" ]]; then
+  echo "Required argument -l(--buildid) or -s(--script)"
+  show_run_help
+  exit 1
+fi
+
+BUILD_ID=${gerritid_lower}-${BUILD_ID}
+INSTANCE_NAME=`echo ${BUILD_ID}-${SUUID} | sed 's/bld/run/'`
+
+if [[ $KEEP_RUNNING == "1" ]]; then
+      MINOR_STEPS_ED[$MAJOR_STEPS]=14
+fi
+#Validate Inputs
+check_run_inputs $BUILD_ID $TEST_SCRIPT
+#Check /home/$USER/.ssh/id_rsa.pub file
+check_file_existence "/home/$USER/.ssh/id_rsa.pub"
+
+printf "\n\n********* RUNID= ${SUUID} *********\n\n"
+
+# If "continue" switch has been given then do following steps
+#   a. Get the RUN-ID provided by user.
+#   b. Get the last successfully completed step.
+#   c. Start the run process from step next to last completed step.
+if [[ $CONTINUE == "1" ]] ; then
+  # User must give the run-id(SUUID generated during first time execution of run process.)
+  # along with continue such that we can know that which "aurora run" he needs to resume.
+  # TODO: Exit if user does not give the run-id.
+  if [ -z ${RUNID+x} ]; then
+    echo "Please provide the RUN-ID which you want to continue e.g. f82ba2b78256"
+    exit
+  fi
+  INSTANCE_NAME=`echo ${BUILD_ID}-${RUNID} | sed 's/bld/run/'`
+  step_rec_file=$WORKSPACE/logs/${INSTANCE_NAME}-last-successful-step
+  LAST_SUCCESSFULL_STEP=( $(<${step_rec_file}) )
+  MINOR_STEPS_ST[$MAJOR_STEPS]=$((LAST_SUCCESSFULL_STEP+1))
+else
+  check_instance_limit
+fi
+
 step_file=$WORKSPACE/logs/${INSTANCE_NAME}-last-successful-step
 DOCK_NAME="pg_dev_${BUILD_ID}:latest"
 INSTANCE_IP=$(get_instance_ip ${INSTANCE_NAME})
@@ -133,8 +171,15 @@ function run_test() {
 
     record_step $step $step_file
     ;;
-
   8)
+    if [[ $LOCAL_CHANGES == 1 ]]; then
+      tryexec push_local_changes ${INSTANCE_IP} ${COMMIT_ID} ${ALPS_PATH}
+      tryexec make_install_alps ${INSTANCE_IP} "/tmp/make_install_alps.log"
+      tryexec run_poll_cmd ${INSTANCE_IP} "make_install_alps.sh" "/tmp/make_install_alps.log" "1"
+      record_step $step $step_file
+    fi
+    ;;
+  9)
     # This is here only untill https://gerrit:8443/#/c/10751/ gets merged.
     echo "Execute the pre run-automaton on docker container"
     local local_file=$(mktemp /tmp/container_preinit.sh-XXXXX)
@@ -157,7 +202,7 @@ function run_test() {
     record_step $step $step_file
     ;;
 
-  9)
+  10)
     if [[ $SKIP_AUTOMATON_INIT != 1 ]]; then
       echo "Execute the run-automaton script on docker container"
       tryexec run_automaton_init ${INSTANCE_IP} "/tmp/automaton_init.log"
@@ -165,7 +210,7 @@ function run_test() {
     fi
     ;;
 
-  10)
+  11)
     if [[ $SKIP_AUTOMATON_INIT != 1 ]]; then
       echo "Poll the automaton-init cmd (tailing \"/tmp/automaton_init.log\" for complete logs)"
       tryexec run_poll_cmd ${INSTANCE_IP} "run_automaton_init.sh" "/tmp/automaton_init.log" "1"
@@ -174,27 +219,27 @@ function run_test() {
     fi
     ;;
 
-  11)
+  12)
     tryexec upload_to_docker ${INSTANCE_IP} ${TEST_SCRIPT} /tmp/user_test_script.sh
     # tryexec is not needed because test can fail as well
     run_cmd_docker_bg ${INSTANCE_IP} "/bin/bash /tmp/user_test_script.sh" "/tmp/test.logs"
     record_step $step $step_file
     ;;
 
-  12)
+  13)
     echo "Poll the test logs (tailing \"/tmp/test.log\")"
     tryexec run_poll_cmd ${INSTANCE_IP} "/tmp/user_test_script.sh" "/tmp/test.logs" "0"
     tryexec download_from_docker ${INSTANCE_IP} "/tmp/test.logs" "${WORKSPACE}/logs/${INSTANCE_NAME}.log"
     record_step $step $step_file
     ;;
 
-  13)
+  14)
     echo "Downloading logs in ${LOG_DIR} directory"
     tryexec get_latest_logs ${INSTANCE_IP} ${INSTANCE_NAME} ${LOG_DIR}
     record_step $step $step_file
     ;;
 
-  14)
+  15)
     echo "Shutting down the Instance ${INSTANCE_NAME}"
     exec_gcloud_cmd instances delete ${INSTANCE_NAME} --delete-disks all  -q
     rm $step_file
diff --git a/aurora/aurora_utils.sh.in b/aurora/aurora_utils.sh.in
--- a/aurora/aurora_utils.sh.in
+++ b/aurora/aurora_utils.sh.in
@@ -2,6 +2,7 @@
 source aurora_infra_settings.conf
 source gc_helpers.sh
 source ~/.aurora.conf
+source help.sh
 
 if [ -z ${gerritid+x} ]; then
   echo "ERROR: gerritid has not been defined. Please make sure to run aurora init. Exiting"
@@ -9,14 +10,18 @@ if [ -z ${gerritid+x} ]; then
 fi
 
 # ***********************************************************************************
-# Function: upload_to_docker_instance_name
+# Function: upload_to_docker_name
 # Purpose : wrapper for upload_to_docker to translate instance name to instance IP
 # Usage   : upload_to_docker_instance_name <Cloud instance name where docker container is running>
 #                            <Local file which needs to be uploaded>
 #                            <path to destination directory>
 # Prereq: Your laptop's key must be already in docker container before this operation
 # ***********************************************************************************
-function upload_to_docker_instance_name() {
+function upload_to_docker_name() {
+  if [[ $# -ne 3 ]]; then
+    show_upload_help
+    exit
+  fi
   local INSTANCE_NAME="${gerritid_lower}-$1"
   local FILE=$2
   local DESTINATION=$3
@@ -25,14 +30,18 @@ function upload_to_docker_instance_name() {
 }
 
 # ***********************************************************************************
-# Function: download_from_docker_instance_name
+# Function: download_from_docker_name
 # Purpose : wrapper for download_from_docker to translate instance name to instance IP
 # Usage   : download_from_instance_name <Cloud instance name where docker container is running>
 #                            <Location of file which needs to be downloaded>
 #                            <Local machine's path where you need to download>
 # Prereq: Your laptop's key must be already in docker container before this operation
 # ***********************************************************************************
-function download_from_docker_instance_name() {
+function download_from_docker_name() {
+  if [[ $# -ne 3 ]]; then
+    show_download_help
+    exit
+  fi
   local INSTANCE_NAME="${gerritid_lower}-$1"
   local FILE=$2
   local DESTINATION=$3
@@ -125,6 +134,7 @@ function list_runids() {
 # Prereq: Aurora init has been called.
 # *****************************************************************************
 function list_disks() {
+  echo "Listing disks for the user:$gerritid"
   # Instances
   local instance_list=$(gcloud compute instances list --format=text --sort-by=creationTimestamp --regexp ".*" | grep ${gerritid_lower} | sed -e "s/${gerritid_lower}-//g")
   local instance_names=($(echo "$instance_list" | grep '^name'))
@@ -251,6 +261,10 @@ function set_max_instances() {
 # Prereq: The instance should exsist.
 # *****************************************************************************
 function login_instance() {
+  if [[ $1 == "help" || -z $1 ]]; then
+    show_login_help
+    exit 1
+  fi
   local INSTANCE_NAME="${gerritid_lower}-$1"
   gcloud compute instances list ${INSTANCE_NAME} | grep "${INSTANCE_NAME}" || RESULT=$? &> /dev/null
   local INSTANCE_IP=$(get_instance_ip ${INSTANCE_NAME})
@@ -261,126 +275,135 @@ function login_instance() {
   fi
   run_cmd_docker_sshforwarding ${INSTANCE_IP} "/bin/bash"
 }
-
-function run_aurora_build() {
-  local REFSPEC=$1
-  local PROJ=$2
-  local BRANCH=$3
-  local TAG=$4
-  local KEEP_RUNNING=$5
-  local CONTINUE=$6
-  local START_STEP=1
-  local END_STEP=21
-
-  #keep_running equalling 1 means -k was specified, end step should be 1 less.
-  if [[ $KEEP_RUNNING == "1" ]]; then
-      END_STEP=20
+# *****************************************************************************
+# Function: list_entities
+# Purpose : Parses the options for aurora ls and calls the respective functions
+# Usage   : list_entities <entity type>
+# Prereq:   aurora init has been called.
+# *****************************************************************************
+function list_entities()
+{
+  if [[ $1 == "help" ]]; then
+    show_ls_help
+    exit 1
   fi
 
-  #Generating Instance name piece by piece
-  local INSTANCE_NAME=${gerritid_lower}
-
-  #Append tag if provided
-  if [[ $TAG != "none" ]]; then
-    #Only keeping alphanumeric characters
-    TAG=${TAG//[^[:alnum:]]/}
-    #Converting to lowercase since instance name cannot contain uppercase characters
-    TAG=${TAG,,}
-    INSTANCE_NAME=${INSTANCE_NAME}-${TAG}
-  fi
-  #Append refspec
-  if [[ $REFSPEC == "none" ]]; then
-    local MOD_BRANCH=$(echo "$BRANCH" | tr _ -)
-    local INSTANCE_NAME=${INSTANCE_NAME}-bld-${MOD_BRANCH}
-  else
-    local MOD_REFSPEC=$(echo "$REFSPEC" | sed -e 's/refs\/changes\///')
-    MOD_REFSPEC=$(echo "$MOD_REFSPEC" | tr /_ -)
-    local INSTANCE_NAME=${INSTANCE_NAME}-bld-${MOD_REFSPEC}
+  if [[ -z "${gerritid}" ]]; then
+    echo "gerrit id not set, please run aurora init"
+    exit 1
   fi
 
-  local step_rec_file=$WORKSPACE/logs/${INSTANCE_NAME}-last-successful-step
-  #Validate Inputs
-  check_build_inputs $INSTANCE_NAME $PROJ $REFSPEC $BRANCH
-  #Check /home/$USER/.ssh/id_rsa.pub file
-  check_file_existance "/home/$USER/.ssh/id_rsa.pub"
-  # If "continue" switch has been given then do following steps
-  #   a. Get the last successfully completed step.
-  #   b. Start the build process from step next to last completed step.
-  if [[ $CONTINUE == "--continue" ]] ; then
-    # Get the last successfull step from /tmp/${INSTANCE_NAME}-last-successful-step
-    LAST_SUCCESSFULL_STEP=( $(<${step_rec_file}) )
-    START_STEP=$((LAST_SUCCESSFULL_STEP+1))
-  else
-    check_instance_limit
-  fi
-
-  #Calulate total build time
-  local start_time=$(date +%s)
-  aurora_build.sh -Q build -R ${START_STEP} -E ${END_STEP} -G ${REFSPEC} -P ${PROJ} -B ${BRANCH} -I ${INSTANCE_NAME}
-  local end_time=$(date +%s)
-  print_time_taken $start_time $end_time "aurora build"
+  case $1 in
+    instances)
+      list_instances ;;
+    snapshots)
+      list_snapshots ;;
+    run)
+      list_runids ;;
+    build)
+      list_buildids ;;
+    disks)
+      list_disks ;;
+    *)
+      list_instances ;;
+  esac
 }
 
 # *****************************************************************************
-# Function: run_aurora_run
-# Purpose : Starting an instance to run test script.
-# Usage   : run_aurora_run <build-id> <test-script>
-#           <flag to keep instance running> <Flag to skip automaton-init step>
-#           <Log directory path> <continue an already proceeding run>
-#           <RUNID which you want to continue>
+# Function: delete_entities
+# Purpose : Parses the options for aurora rm and calls the respective functions
+# Usage   : delete_entities <entity type> <regex>
+# Prereq:   aurora init has been called.
 # *****************************************************************************
-function run_aurora_run() {
-  local USER_BUILD_ID=$1
-  local TEST_SCRIPT=$2
-  local KEEP_RUNNING=$3
-  local SKIP_AUTOMATON_INIT=$4
-  local log_dir=$5
-  local CONTINUE=$6
-  local RUNID=$7
-
-  local START_STEP=1
-  local END_STEP=14
-  local UUID=`uuidgen`
-  local SUUID_="${UUID##*-}"
-  SUUID="${SUUID_,,}"
-  BUILD_ID=${gerritid_lower}-${USER_BUILD_ID}
-  local INSTANCE_NAME=`echo ${BUILD_ID}-${SUUID} | sed 's/bld/run/'`
-  local step_rec_file=$WORKSPACE/logs/${INSTANCE_NAME}-last-successful-step
-
-  #keep_running equalling 1 means -k was specified, end step should be 1 less.
-  # TODO: Need to replace following code. Everytime, some new step gets added
-  # or deleted, following value will need modification. High probability of miss.
-  # We can define build and run steps in conf file and should start using those
-  # values everywhere.
-  if [[ $KEEP_RUNNING == "1" ]]; then
-      END_STEP=13
+function delete_entities()
+{
+  if [[ $1 == "help" || $# -lt 2 ]]; then
+    show_rm_help
+    exit 1
   fi
-  #Validate Inputs
-  check_run_inputs $BUILD_ID $TEST_SCRIPT
-  #Check /home/$USER/.ssh/id_rsa.pub file
-  check_file_existance "/home/$USER/.ssh/id_rsa.pub"
-  # If "continue" switch has been given then do following steps
-  #   a. Get the RUN-ID provided by user.
-  #   b. Get the last successfully completed step.
-  #   c. Start the run process from step next to last completed step.
-  if [[ $CONTINUE == "--continue" ]] ; then
-    # User must give the run-id(SUUID generated during first time execution of run process.)
-    # along with continue such that we can know that which "aurora run" he needs to resume.
-    # TODO: Exit if user does not give the run-id.
-    if [ -z ${RUNID+x} ]; then
-      echo "Please provide the RUN-ID which you want to continue e.g. f82ba2b78256"
-      exit
-    fi
-    INSTANCE_NAME=`echo ${BUILD_ID}-${RUNID} | sed 's/bld/run/'`
-    local step_rec_file=/tmp/${INSTANCE_NAME}-last-successful-step
-    LAST_SUCCESSFULL_STEP=( $(<${step_rec_file}) )
-    START_STEP=$((LAST_SUCCESSFULL_STEP+1))
+
+  if [[ -z "${gerritid}" ]]; then
+    echo "gerrit id not set, please run aurora init"
+    exit 1
+  fi
+
+  case $1 in
+    instances)
+      delete_instances $2 $3 ;;
+    snapshots)
+      delete_snapshots $2 $3 ;;
+    disks)
+      delete_disks $2 $3;;
+    *)
+      show_rm_help;;
+  esac
+}
+# *****************************************************************************
+# Function: run_debug_test
+# Purpose : Parses the options for debug-test for local and non-local changes
+# Usage   : run_debug_test <arguments>
+# Prereq:   aurora init has been called.
+# *****************************************************************************
+function run_debug_test() {
+  local TEMP=`getopt -o W:l:i:n:s:La:c:h --long WORKSPACE:,buildid:,test_iterations:,num_instances:,script:,local-changes,commit:,alps-path,\help -n 'aurora.sh' -- "$@"`
+eval set -- "$TEMP"
+
+TEST_ITERATIONS=1
+NUM_INSTANCES=1
+LOCAL_CHANGES_ENABLED=0
+ALPS_PATH=/home/${USER}/work/alps
+# extract options and their arguments into variables.
+while true ; do
+  case "$1" in
+    -W| --WORKSPACE) export WORKSPACE=$2 ; shift 2 ;;
+    -l|--buildid) BUILD_ID=$2 ; shift 2 ;;
+    -i|--test_iterations) TEST_ITERATIONS=$2 ; shift 2 ;;
+    -s|--script) USER_SCRIPT=$2 ; shift 2 ;;
+    -n|--num_instances) NUM_INSTANCES=$2 ; shift 2 ;;
+#Optional argments for local changes transfer
+    -L|--local-changes) LOCAL_CHANGES_ENABLED="1"; shift ;;
+    -c|--commit) COMMIT_HASH=$2 ; shift 2 ;;
+    -a|--alps-path) ALPS_PATH=$2 ; shift 2 ;;
+    -h|--help)
+      show_debug_test_help
+      exit 0
+      shift ;;
+    --) shift ; break ;;
+    *)
+      echo "Unrecognized option $1"
+       exit 1 ;;
+  esac
+done
+
+if [[ -z "$BUILD_ID" || -z "$USER_SCRIPT"  ]]; then
+  echo "Missing required arguments"
+  show_debug_test_help
+  exit 1
+fi
+check_file_existence "$USER_SCRIPT"
+
+if [[ "$LOCAL_CHANGES_ENABLED" == "1" ]]; then
+  #Check if ALPS_PATH is correct
+  local retval=0
+  git rev-parse --resolve-git-dir $ALPS_PATH/.git || retval=$?
+  if [[ $retval != "0" ]]; then
+    echo "Alps not found at :$ALPS_PATH"
+    echo "Use the -a(--alps-path) to specify the path to alps"
+    exit 1
+  fi
+  if [[ -z "$COMMIT_HASH" ]]; then
+    echo "Missing required argument for transferring local changes"
+    show_debug_test_help
+    exit 1
   else
-    check_instance_limit
+    #Run with local changes
+    run_pipelines.sh -P "DEBUG-TEST" --base_script_dir "@CMAKE_CURRENT_BINARY_DIR@/pipeline_scripts/alps/" -i $TEST_ITERATIONS -s $USER_SCRIPT\
+ -n $NUM_INSTANCES -l $BUILD_ID -L -a $ALPS_PATH -c $COMMIT_HASH
   fi
-  #Calulate total run time
-  local start_time=$(date +%s)
-  aurora_run.sh -Q run -R ${START_STEP} -E ${END_STEP} -B ${BUILD_ID} -T ${TEST_SCRIPT} -U ${SUUID} -I ${INSTANCE_NAME} --skip-automaton-init ${SKIP_AUTOMATON_INIT} -o ${log_dir}
-  local end_time=$(date +%s)
-  print_time_taken $start_time $end_time "aurora run"
+else
+  #Run without local changes
+  run_pipelines.sh -P "DEBUG-TEST" --base_script_dir "@CMAKE_CURRENT_BINARY_DIR@/pipeline_scripts/alps/" -i $TEST_ITERATIONS -s $USER_SCRIPT\
+ -n $NUM_INSTANCES -l $BUILD_ID
+fi
+
 }
diff --git a/aurora/gc_helpers.sh.in b/aurora/gc_helpers.sh.in
--- a/aurora/gc_helpers.sh.in
+++ b/aurora/gc_helpers.sh.in
@@ -14,6 +14,10 @@ if [[ ! -d "${WORKSPACE}/logs" ]] ; then
 fi
 
 function init_id() {
+  if [[ $1 == "help" ]] ; then
+    show_init_help
+    exit 1
+  fi
   conf_file="/home/$USER/.aurora.conf"
   echo "Please enter your gerrit id: "
   read gerritid
@@ -142,6 +146,35 @@ function run_cmd_docker_sshforwarding_bg() {
   local LOG_FILE=$3
 
   run_cmd_gci_sshforwarding ${INSTANCE_IP} "ssh -t -o StrictHostKeyChecking=no plumgrid@\`cat local_docker_ip\` \" nohup bash -c '${DOCKER_CMD} > ${LOG_FILE} 2>&1 &' \""
+}
+
+
+# *****************************************************************************
+# Function: push_local_changes
+# Purpose : Pushes the specified local changes to the docker container.
+# Usage   : push_local_changes
+# Prereq: Aurora init has been called.
+# *****************************************************************************
+function push_local_changes() {
+  local INSTANCE_IP=$1
+  local COMMIT_ID=$2
+  local ALPS_PATH=$3
+
+  cd $ALPS_PATH
+  #Get branch name from commit
+  local BRANCH=$(git branch --contains $COMMIT_ID | cut -d ' ' -f 2)
+  local DOCKER_IP=$(get_docker_ip ${INSTANCE_IP})
+  run_cmd_docker ${INSTANCE_IP} "git config  -f /home/plumgrid/work/alps/.git/config receive.denyCurrentBranch ignore"
+  local local_file=$(mktemp /tmp/ssh-command-XXXXX)
+  #Proxy command to SSH directly into the docker container
+  echo "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  -o \"ProxyCommand ssh ${INSTANCE_IP} nc ${DOCKER_IP} 22\" \$*" > ${local_file}
+  #Has to be executable
+  chmod +x $local_file
+  #Push the changes
+  cd $ALPS_PATH;GIT_SSH="${local_file}" git push plumgrid@${DOCKER_IP}:/home/plumgrid/work/alps $COMMIT_ID:$BRANCH
+  #Checkout the branch
+  run_cmd_docker ${INSTANCE_IP} "git --git-dir=/home/plumgrid/work/alps/.git --work-tree=/home/plumgrid/work/alps checkout $BRANCH"
+  rm ${local_file}
 }
 
 # *****************************************************************************
@@ -324,6 +357,17 @@ function get_latest_snapshot_id() {
   echo $ssid
 }
 # *****************************************************************************
+# Function: get_docker_ip
+# Purpose : Gets the  IP address of the docker container.
+# Usage   : get_docker_ip <instance IP>
+# *****************************************************************************
+function get_docker_ip() {
+local INSTANCE_IP=$1
+local DOCKER_IP=$(run_cmd_gci ${INSTANCE_IP} "cat /home/$USER/local_docker_ip")
+
+echo -n "$DOCKER_IP"
+}
+# *****************************************************************************
 # Function: get_instance_ip
 # Purpose : Gets the internal IP address of the instance.
 # Usage   : get_instance_ip <instance name>
@@ -440,6 +484,29 @@ function run_bg_cmd() {
   #Run the command in the background
   tryexec run_cmd_docker_sshforwarding_bg ${INSTANCE_IP} "$CMD" "$LOG_FILE"
 
+}
+# ******************************************************************************
+# Function: make_install_alps
+# Purpose : Creates a script for running building alps, uploads and runs the script
+#           on the docker container. The return value for the install is echoed to
+#           check for failure.
+# Usage   : make_install_alps <cloud_instance_ip> <log file>
+# ******************************************************************************
+function make_install_alps() {
+  local INSTANCE_IP=$1
+  local LOG_FILE=$2
+  local local_file=$(mktemp /tmp/make_install_alps-XXXXX)
+  cat /dev/null > ${local_file}
+  echo "cd /home/plumgrid/work/alps/build;" >> ${local_file}
+  echo "cmake ..;" >> ${local_file}
+  echo "make -j4 install" >> ${local_file}
+  tryexec upload_to_docker ${INSTANCE_IP}  ${local_file} ${local_file}
+  #File name needs to be constant for continue functionality, thus renaming.
+  local docker_file=$(dirname $local_file)
+  docker_file="${docker_file}/make_install_alps.sh"
+  tryexec run_cmd_docker ${INSTANCE_IP} "mv ${local_file} ${docker_file}"
+  rm ${local_file}
+  tryexec run_bg_cmd ${INSTANCE_IP} ${docker_file} "/bin/bash ${docker_file}" "$LOG_FILE"
 }
 # ******************************************************************************
 # Function: run_build_all
@@ -817,14 +884,14 @@ function retryexec() {
 }
 
 # *****************************************************************************
-# Function: check_file_existance
+# Function: check_file_existence
 # Purpose : Checks if the file exists.
-# Usage   : check_file_existance <Path with filename>
+# Usage   : check_file_existence <Path with filename>
 # Prereq  :
 # *****************************************************************************
-function check_file_existance() {
+function check_file_existence() {
   if [ ! -f "$1" ] ; then
-    echo "$1 does not exists!"
+    echo "$1 does not exist!"
     exit 1
   fi
 }
diff --git a/aurora/pipeline_scripts/alps/run_pipelines.sh.in b/aurora/pipeline_scripts/alps/run_pipelines.sh.in
--- a/aurora/pipeline_scripts/alps/run_pipelines.sh.in
+++ b/aurora/pipeline_scripts/alps/run_pipelines.sh.in
@@ -1,12 +1,16 @@
 #!/bin/bash -e
 export PATH=@CMAKE_BINARY_DIR@/:/opt/pg/scripts:/opt/pg/scripts/gcloud/aurora/pipeline_scripts/alps:$PATH
-
 source /home/$USER/.aurora.conf
 source pl_utils.sh
 source pl_help.sh
 source pl_settings.conf
 source gc_helpers.sh
 
+#Show help
+if [[ $3 == "help" ]]; then
+  show_run_tests_help
+  exit 1
+fi
 declare -A MINOR_STEPS_ST
 declare -A MINOR_STEPS_ED
 BUILD_ENV_USER=${USER}
@@ -15,42 +19,38 @@ MINOR_STEPS_ST[run]=1
 MINOR_STEPS_ED[run]=6
 DEST_SCRIPT_DIR=0
 
+#Options arguments to forward to run
+OPT_RUN_ARGS=""
 echo " ***** WORKSPACE=${WORKSPACE} ***** "
 echo "@CMAKE_CURRENT_BINARY_DIR@/run_pipelines.sh $@"
 # read the options
-TEMP=`getopt -o Q:R:E:l:p:i:f:P:t:n:\r:d:IFh --long major:,minor_start:,minor_end:,buildid:,pipeline:,test_iterations:,first_test:,step_size:,num_instances:,base_script_dir:,dest_script_dir:,initial_run,db_update\help -n 'run_all_test.sh' -- "$@"`
+TEMP=`getopt -o Q:R:E:l:W:s:a:i:Lc:f:P:t:n:\r:d:IFh --long major:,commit:,local-changes,WORKSPACE:,minor_start:,script:,minor_end:,buildid:,alps-path:,pipeline:,test_iterations:,first_test:,step_size:,num_instances:,base_script_dir:,dest_script_dir:,initial_run,db_update\help -n 'run_all_test.sh' -- "$@"`
 eval set -- "$TEMP"
 
 # extract options and their arguments into variables.
 while true ; do
   case "$1" in
-    -Q|--major)
-      MAJOR_STEPS="$2"; shift 2 ;;
-    -R|--minor_start )
-      MINOR_STEPS_ST[$MAJOR_STEPS]="$2"; shift 2 ;;
-    -E|--minor_end )
-      MINOR_STEPS_ED[$MAJOR_STEPS]="$2"; shift 2 ;;
+    -Q|--major) MAJOR_STEPS="$2"; shift 2 ;;
+    -R|--minor_start ) MINOR_STEPS_ST[$MAJOR_STEPS]="$2"; shift 2 ;;
+    -E|--minor_end ) MINOR_STEPS_ED[$MAJOR_STEPS]="$2"; shift 2 ;;
+    -W| --WORKSPACE) export WORKSPACE=$2 ; shift 2 ;;
     -l|--buildid)
       echo "-l = $2"
       USER_BUILD_ID=$2 ; shift 2 ;;
-    -P|--pipeline)
-      PIPELINE=$2 ; shift 2 ;;
-    -i|--test_iteratons)
-      TEST_ITERATIONS=$2 ; shift 2 ;;
-    -f|--first_test)
-      FIRST_TEST=$2 ; shift 2 ;;
-    -t|--step_size)
-      STEP_SIZE=$2 ; shift 2 ;;
-    -n|--num_instances)
-      NUM_INSTANCES=$2 ; shift 2 ;;
-    -r|--base_script_dir)
-        BASE_SCRIPT_DIR=$2 ; shift 2;;
-    -d|--dest_script_dir)
-        DEST_SCRIPT_DIR=$2 ; shift 2;;
-    -I|--initial_run)
-        INITIAL_RUN="true" ; shift ;;
-    -F|--db_update)
-        DB_UPDATE="true" ; shift ;;
+    -P|--pipeline) PIPELINE=$2 ; shift 2 ;;
+    -i|--test_iterations) TEST_ITERATIONS=$2 ; shift 2 ;;
+    -f|--first_test) FIRST_TEST=$2 ; shift 2 ;;
+    -t|--step_size) STEP_SIZE=$2 ; shift 2 ;;
+    -s|--script) USER_SCRIPT=$2 ; shift 2 ;;
+    -n|--num_instances) NUM_INSTANCES=$2 ; shift 2 ;;
+    -r|--base_script_dir) BASE_SCRIPT_DIR=$2 ; shift 2;;
+    -d|--dest_script_dir) DEST_SCRIPT_DIR=$2 ; shift 2;;
+    -I|--initial_run) INITIAL_RUN="true" ; shift ;;
+    -F|--db_update) DB_UPDATE="true" ; shift ;;
+#Optional argments for local changes transfer
+    -L|--local-changes) OPT_RUN_ARGS="$OPT_RUN_ARGS -L"; shift ;;
+    -c|--commit) OPT_RUN_ARGS="$OPT_RUN_ARGS -c $2" ; shift 2 ;;
+    -a|--alps-path)   OPT_RUN_ARGS="$OPT_RUN_ARGS -a $2" ; shift 2 ;;
     -h|--help)
       show_run_tests_help
       exit 0
@@ -77,8 +77,9 @@ MOD_BUILD_ID=`echo ${BUILD_ID} | sed 's/bld/run/'`
 script_dir=$(get_script_dir $WORKSPACE $DEST_SCRIPT_DIR $PIPELINE $MOD_BUILD_ID)
 log_dir=${script_dir}/logs
 untar_log_dir=${script_dir}/untar_logs
-db=$(get_db $PIPELINE)
-
+if [[ $PIPELINE != "DEBUG-TEST" ]]; then
+  db=$(get_db $PIPELINE)
+fi
 #echo "./run_pipelines.sh -l $USER_BUILD_ID -p $PIPELINE -i $TEST_ITERATIONS -f $FIRST_TEST -t $STEP_SIZE -n $NUM_INSTANCES -r $BASE_SCRIPT_DIR= -d $DEST_SCRIPT_DIR -I $INITIAL_RUN -F $FORCE_DB_UPDATE"
 
 function run_test() {
@@ -88,15 +89,24 @@ function run_test() {
   1)
     # Generate scripts to be used by "aurora run"
     echo "Going to generate test scripts"
-    echo "gen_test_scripts.sh -b ${base_script} -i ${TEST_ITERATIONS} -f ${FIRST_TEST} -t ${STEP_SIZE} -n ${NUM_INSTANCES} -d ${script_dir} -I ${INITIAL_RUN} -D ${db} -r ${BASE_SCRIPT_DIR}"
-    gen_test_scripts.sh -p $PIPELINE -b ${BASE_SCRIPT} -i ${TEST_ITERATIONS} -f ${FIRST_TEST} -t ${STEP_SIZE} -n ${NUM_INSTANCES} -d ${script_dir} -I ${INITIAL_RUN} -D ${db} --base_script_dir $BASE_SCRIPT_DIR
+    echo "gen_test_scripts.sh -b ${BASE_SCRIPT} -i ${TEST_ITERATIONS} -f ${FIRST_TEST} -t ${STEP_SIZE} -n ${NUM_INSTANCES} -d ${script_dir} -I ${INITIAL_RUN} -D ${db} -r ${BASE_SCRIPT_DIR}"
+    if [[ $PIPELINE == "DEBUG-TEST" ]]; then
+      gen_user_tests.sh -b ${BASE_SCRIPT} -i ${TEST_ITERATIONS} -n ${NUM_INSTANCES} -d ${script_dir} --base_script_dir $BASE_SCRIPT_DIR -s ${USER_SCRIPT}
+    else
+      gen_test_scripts.sh -p $PIPELINE -b ${BASE_SCRIPT} -i ${TEST_ITERATIONS} -f ${FIRST_TEST} -t ${STEP_SIZE} -n ${NUM_INSTANCES} -d ${script_dir} -I ${INITIAL_RUN} -D ${db} --base_script_dir $BASE_SCRIPT_DIR
+    fi
+
     ;;
 
   2)
     echo "log_dir=$log_dir script_dir=$script_dir"
     while read -r -d $'\0'; do
       #echo "aurora run -l ${USER_BUILD_ID} -s $REPLY -o ${log_dir} -S"
-      aurora run -l ${USER_BUILD_ID} -o ${log_dir} -s $REPLY -S > $REPLY.txt 2>&1 &
+      if [[ $PIPELINE == "DEBUG-TEST" ]]; then
+        aurora run -l ${USER_BUILD_ID} -o ${log_dir} -s $REPLY -S $OPT_RUN_ARGS > $REPLY.txt 2>&1 &
+      else
+        aurora run -l ${USER_BUILD_ID} -o ${log_dir} -s $REPLY -S $OPT_RUN_ARGS > $REPLY.txt 2>&1 &
+      fi
     done < <(find ${script_dir} -name "*.sh-*" -print0)
     sleep 30
     ;;
@@ -145,7 +155,7 @@ __HEREDOC
       failed_list=$(find ${untar_log_dir} -name "*FAILED.log")
       for test in ${failed_list[@]}; do
         test=$(basename "$test")
-        test=$(echo "$test" | sed 's/ctestout_iter[0-9]*_//' | sed 's/.FAILED.log//' )
+        test=$(echo "$test" | sed 's/ctestout_inst*_//' | sed 's/.FAILED.log//' )
         echo "* $test" >> ${WORKSPACE}/status-message.log
       done
       echo >> "${WORKSPACE}/status-message.log"
@@ -185,8 +195,6 @@ __HEREDOC
       ./build_db.sh -D ${db} -d ${untar_log_dir} > ${untar_log_dir}/DB_REPORT.txt
       cat ${untar_log_dir}/DB_REPORT.txt
       printf "\n\n******* Updation of database has been completed. Please see ${untar_log_dir}/DB_REPORT.txt ******\n\n"
-    else
-      echo "Not going to update the Database"
     fi
 
     if [[ $num_failures -eq 0 ]]; then
