INFRA-645: ssh-agent getting stale while running remote commands
Change-Id: I4317186bacb1b21ba446dfd06671fc09e5ccc227
Signed-off-by: Jannet Faiz <jannet@plumgrid.com>

diff --git a/aurora/aurora_build.sh.in b/aurora/aurora_build.sh.in
--- a/aurora/aurora_build.sh.in
+++ b/aurora/aurora_build.sh.in
@@ -167,15 +167,37 @@ function build_image() {
     tryexec write_gitsync.sh "${GIT_SYNC_SCRIPT}" "${BRANCH}" "${PROJECT}" "${REFSPEC}"
     tryexec upload_to_docker ${INSTANCE_IP} ${GIT_SYNC_SCRIPT} /tmp/
     tryexec run_cmd_docker ${INSTANCE_IP} "mv ${GIT_SYNC_SCRIPT} /tmp/gitsync.sh"
-    rm ${GIT_SYNC_SCRIPT}
+    #rm ${GIT_SYNC_SCRIPT}
     record_step $step $step_file
     ;;
 
   10)
-    echo "Execute the gitsynch script on docker container"
+    echo "Execute the gitsynch script on docker container in steps"
+    # Run Step1: cleanup
+    tryexec run_cmd_docker_sshforwarding ${INSTANCE_IP} "bash /tmp/gitsync.sh 1"
+
+    # Run Step2: Fetch tools
     pkill "ssh-agent" || true
     tryexec check_ssh_server_status ${INSTANCE_IP}
-    tryexec run_cmd_docker_sshforwarding ${INSTANCE_IP} "bash /tmp/gitsync.sh"
+    tryexec run_cmd_docker_sshforwarding ${INSTANCE_IP} "bash /tmp/gitsync.sh 2"
+
+    # Run Step3: Fetch all repos
+    for p in ${PROJECT_LIST[@]}; do
+      pkill "ssh-agent" || true
+      tryexec check_ssh_server_status ${INSTANCE_IP}
+      tryexec run_cmd_docker_sshforwarding ${INSTANCE_IP} "bash /tmp/gitsync.sh 3 $p"
+    done
+
+    # Run Step4: Fetch iovisor
+    pkill "ssh-agent" || true
+    tryexec check_ssh_server_status ${INSTANCE_IP}
+    tryexec run_cmd_docker_sshforwarding ${INSTANCE_IP} "bash /tmp/gitsync.sh 4"
+
+    # Checkout the required changes for specified project and build repos
+    pkill "ssh-agent" || true
+    tryexec check_ssh_server_status ${INSTANCE_IP}
+    tryexec run_cmd_docker_sshforwarding ${INSTANCE_IP} "bash /tmp/gitsync.sh 5"
+
     record_step $step $step_file
     ;;
 
diff --git a/aurora/write_gitsync.sh.in b/aurora/write_gitsync.sh.in
--- a/aurora/write_gitsync.sh.in
+++ b/aurora/write_gitsync.sh.in
@@ -39,7 +39,14 @@ cat /dev/null > ${git_script}
 echo "#!/bin/bash -e" >> ${git_script}
 echo "set -e" >> ${git_script}
 echo ". /opt/pg/env/alps.bashrc" >> ${git_script}
+echo "step=\$1" >> ${git_script}
+echo "repo=\$2" >> ${git_script}
 
+# STEP-1: cleanup
+cat >> ${git_script} <<DELIM__
+case \$step in
+  1)
+DELIM__
 #GPG keys expire after ~10 days, after which /opt/pg/var/www needs to
 #be nuked for master as well and fresh build-all.sh needs to be run
 echo "echo 'Performing cleanup'" >> ${git_script}
@@ -49,6 +56,11 @@ for p in ${PROJECT_LIST[@]}; do
 done
 echo "rm -rf /opt/pg/systest" >> ${git_script}
 
+# STEP-2: Fetch tools
+cat >> ${git_script} <<DELIM__
+    ;;
+  2)
+DELIM__
 ## Update and install the tools in the snapshot in case some new packages were added.
 modify_git_config "tools" "${gerritid}" "${git_script}"
 echo "echo 'Extracting and rebuild tools'"  >> ${git_script}
@@ -57,17 +69,25 @@ echo "git fetch" >> ${git_script}
 echo "git checkout master"  >> ${git_script}
 echo "git reset --hard origin/master" >> ${git_script}
 
+# STEP-3: Fetch all repos
+cat >> ${git_script} <<DELIM__
+    ;;
+  3)
+DELIM__
 ## Checkout the requested branch on all the projects
-for p in ${PROJECT_LIST[@]}; do
-  modify_git_config "${p}" "${gerritid}" "${git_script}"
-  echo "echo \"Extracting and rebuilding $p for branch ${branch}\""
-  echo "cd /home/plumgrid/work/${p}" >> ${git_script}
-  echo "git fetch" >> ${git_script}
-  echo "git reset --hard origin/${branch}" >> ${git_script}
-  echo "git checkout ${branch}" >> ${git_script}
-  echo "git reset --hard origin/${branch}" >> ${git_script}
-done
+modify_git_config "\${repo}" "${gerritid}" "${git_script}"
+echo "echo \"Extracting and rebuilding \${repo} for branch ${branch}\""
+echo "cd /home/plumgrid/work/\${repo}" >> ${git_script}
+echo "git fetch" >> ${git_script}
+echo "git reset --hard origin/${branch}" >> ${git_script}
+echo "git checkout ${branch}" >> ${git_script}
+echo "git reset --hard origin/${branch}" >> ${git_script}
 
+# Step-4: Fetch iovisor
+cat >> ${git_script} <<DELIM__
+    ;;
+  4)
+DELIM__
 ## Update and install iovisor.
 modify_git_config "iovisor" "${gerritid}" "${git_script}"
 echo "echo 'Getting right version of iovisor'"  >> ${git_script}
@@ -81,6 +101,13 @@ echo "git reset --hard \${git_dep_branch[iovisor]}" >> ${git_script}
 echo "cd /home/plumgrid/work/pkg/scripts" >> $git_script
 echo "sed -i \"/export APT_REPO_HOST/ c\export APT_REPO_HOST=127.0.0.1 && export APT_COMPONENT=${APT_COMPONENT}\" build-all.sh" >> $git_script
 
+# Step-5: -- Checkout the required changes for the defined porject
+#         -- Build tools and iovisor
+#         -- Set apt-component on the repos and run cmake .. again
+cat >> ${git_script} <<DELIM__
+    ;;
+  5)
+DELIM__
 if [[ "$refspec" =~ refs/changes/* ]]; then
   ## Checkout the request commit in the request project
   echo "cd /home/plumgrid/work/${project}" >> $git_script
@@ -113,3 +140,11 @@ done
 echo "cd /home/plumgrid/work/${project}/build" >> ${git_script}
 echo "export APT_COMPONENT=${APT_COMPONENT}" >> ${git_script}
 echo "cmake .." >> ${git_script}
+cat >> ${git_script} <<DELIM__
+    ;;
+  *)
+    echo "Step \$step provided is invalid. Exiting!"
+    exit 1
+esac
+DELIM__
+
