Added support for Aurora shutdown
USAGE: aurora shutdown <ENTITY> <REGEX> [-f --force]
       Shuts down the ENTITY containing value in REGEX

<ENTITY>              Value can be:
                      "instances"
<REGEX>               Regex to match. e.g "run" will delete all instances or snapshots
                      having 'run' as part of name.
Options:
-f, --force           Suppresses user confirmation

Ticket: [851]
Change-Id: Ic78c13512791b3ae718fa18eb64195d966b0a652
Signed-off-by: Muaaz Saleem <muaazs@plumgrid.com>

diff --git a/aurora/aurora_utils.sh.in b/aurora/aurora_utils.sh.in
--- a/aurora/aurora_utils.sh.in
+++ b/aurora/aurora_utils.sh.in
@@ -165,6 +165,40 @@ function list_disks() {
   done
   echo "------------------------------------------------"
 }
+
+# *****************************************************************************
+# Function: shutdown_instances
+# Purpose : Shuts down the cloud instances currently running for the user. Much like a laptop.
+# Usage   : shutdown_user_instances
+# Prereq: Aurora init has been called.
+# *****************************************************************************
+function shutdown_instances() {
+  local REGEX=".*$1.*"
+  local user_instances=$(gcloud compute instances list --regexp "${REGEX}" | grep ${emailid} | cut -d ' ' -f 1)
+
+  if [[ -z ${user_instances} ]]; then
+   echo "No such instances found"
+   exit
+  fi
+
+  echo "The following instances will be shutdown: "
+  for instance in $user_instances; do
+    echo "$instance"
+  done
+
+  if [ "$2" != "-f" -a "$2" != "--force" ]; then
+    read -r -p "Are you sure you want to continue? (y/N)" response
+    response=${response,,}    # tolower
+    if [[ $response =~ ^(yes|y)$ ]]; then
+      echo "Proceeding with shutdown..."
+    else
+      exit
+    fi
+  fi
+  user_instances=$(echo "${user_instances}" | tr '\n' ' ')
+  gcloud compute instances stop $user_instances -q
+}
+
 # *****************************************************************************
 # Function: delete_instances
 # Purpose : Deletes the cloud instances currently running for the user.
@@ -332,6 +366,33 @@ function list_entities()
     *)
       echo "Invalid entity for aurora ls"
       show_ls_help ;;
+  esac
+}
+
+# *****************************************************************************
+# Function: shutdown_entities
+# Purpose : Parses the options for aurora shutdown and calls the respective functions
+# Usage   : shutdown_entities <entity type> <regex>
+# Prereq:   aurora init has been called.
+# *****************************************************************************
+function shutdown_entities()
+{
+  if [[ $1 == "help" || $# -lt 2 ]]; then
+    show_shutdown_help
+    exit 1
+  fi
+
+  if [[ -z "${gerritid}" || -z "${emailid}"  ]]; then
+    echo "gerritid or email not set, please run aurora init"
+    exit 1
+  fi
+
+  case $1 in
+    instances)
+      shutdown_instances $2 $3 ;;
+    *)
+      echo "Invalid entity for aurora rm"
+      show_shutdown_help;;
   esac
 }
 
