Added support for Aurora start
USAGE: aurora start <ENTITY> <REGEX> [-f --force]
       Starts the ENTITY containing value in REGEX

<ENTITY>              Value can be:
                      "instances"
<REGEX>               Regex to match. e.g "run" will start all instances
                      having 'run' as part of name.
Options:
-f, --force           Suppresses user confirmation

Ticket: [INFRA-851]

Change-Id: Ia4a92a73105870addfca1595d2067937544f34b9
Signed-off-by: Muaaz Saleem <muaazs@plumgrid.com>

diff --git a/aurora/aurora_utils.sh.in b/aurora/aurora_utils.sh.in
--- a/aurora/aurora_utils.sh.in
+++ b/aurora/aurora_utils.sh.in
@@ -167,6 +167,39 @@ function list_disks() {
 }
 
 # *****************************************************************************
+# Function: start_instances
+# Purpose : Starts the cloud instances currently shutdown for the user. Much like a laptop.
+# Usage   : start_user_instances
+# Prereq: Aurora init has been called. Aurora shutdown has been called.
+# *****************************************************************************
+function start_instances() {
+  local REGEX=".*$1.*"
+  local user_instances=$(gcloud compute instances list --regexp "${REGEX}" | grep ${emailid} | cut -d ' ' -f 1)
+
+  if [[ -z ${user_instances} ]]; then
+   echo "No such instances found"
+   exit
+  fi
+
+  echo "The following instances will be started: "
+  for instance in $user_instances; do
+    echo "$instance"
+  done
+
+  if [ "$2" != "-f" -a "$2" != "--force" ]; then
+    read -r -p "Are you sure you want to continue? (y/N)" response
+    response=${response,,}    # tolower
+    if [[ $response =~ ^(yes|y)$ ]]; then
+      echo "Proceeding with startup..."
+    else
+      exit
+    fi
+  fi
+  user_instances=$(echo "${user_instances}" | tr '\n' ' ')
+  gcloud compute instances start $user_instances -q
+}
+
+# *****************************************************************************
 # Function: shutdown_instances
 # Purpose : Shuts down the cloud instances currently running for the user. Much like a laptop.
 # Usage   : shutdown_user_instances
@@ -370,6 +403,33 @@ function list_entities()
 }
 
 # *****************************************************************************
+# Function: start_entities
+# Purpose : Parses the options for aurora start and calls the respective functions
+# Usage   : start_entities <entity type> <regex>
+# Prereq:   aurora init has been called.
+# *****************************************************************************
+function start_entities()
+{
+  if [[ $1 == "help" || $# -lt 2 ]]; then
+    show_start_help
+    exit 1
+  fi
+
+  if [[ -z "${gerritid}" || -z "${emailid}"  ]]; then
+    echo "gerritid or email not set, please run aurora init"
+    exit 1
+  fi
+
+  case $1 in
+    instances)
+      start_instances $2 $3 ;;
+    *)
+      echo "Invalid entity for aurora start"
+      show_start_help ;;
+  esac
+}
+
+# *****************************************************************************
 # Function: shutdown_entities
 # Purpose : Parses the options for aurora shutdown and calls the respective functions
 # Usage   : shutdown_entities <entity type> <regex>
@@ -391,7 +451,7 @@ function shutdown_entities()
     instances)
       shutdown_instances $2 $3 ;;
     *)
-      echo "Invalid entity for aurora rm"
+      echo "Invalid entity for aurora shutdown"
       show_shutdown_help;;
   esac
 }
