Docker Removal: combined commit
Added patch provided by AliR to resolve build failure.
Ali successfully ran build 30 times without any issue.

Change-Id: I41c5bbf5ca70b31eaece4e636ff2306f0e7a00cb
Signed-off-by: trauf <tahir@plumgrid.com>

diff --git a/aurora/aurora_run.sh.in b/aurora/aurora_run.sh.in
--- a/aurora/aurora_run.sh.in
+++ b/aurora/aurora_run.sh.in
@@ -20,18 +20,16 @@ declare -A MINOR_STEPS_ST
 declare -A MINOR_STEPS_ED
 MAJOR_STEPS="run"
 MINOR_STEPS_ST[$MAJOR_STEPS]=1
-MINOR_STEPS_ED[$MAJOR_STEPS]=16
+MINOR_STEPS_ED[$MAJOR_STEPS]=13
 
 UUID=`uuidgen`
 SUUID_="${UUID##*-}"
 SUUID="${SUUID_,,}"
-
 TAG="none"
 AUTOMATON_INIT=0
 CONTINUE=0
 KEEP_RUNNING=0
 LOCAL_CHANGES=0
-
 
 # read the options
 TEMP=`getopt -o l:s:o:n:t:W:CAKhLc:a:R:E: --long buildid:,tag:,script:,log_dir:,runid:,WORKSPACE:,\continue,automaton-init,keep-running,\help,\local-changes,commit:,alps-path:,minor_st:,minor_end: -n 'aurora.sh' -- "$@"`
@@ -96,7 +94,7 @@ if [ ${#INSTANCE_NAME} -gt "58" ]; then
 fi
 
 if [[ $KEEP_RUNNING == "1" ]]; then
-  MINOR_STEPS_ED[$MAJOR_STEPS]=15
+  MINOR_STEPS_ED[$MAJOR_STEPS]=12
 fi
 #Validate Inputs
 check_run_inputs $BUILD_ID
@@ -104,7 +102,7 @@ check_run_inputs $BUILD_ID
 if [[ -n $TEST_SCRIPT ]]; then
   check_file_existence $TEST_SCRIPT
 else
-  MINOR_STEPS_ED[$MAJOR_STEPS]=12
+  MINOR_STEPS_ED[$MAJOR_STEPS]=9
 fi
 #Check /home/$USER/.ssh/id_rsa.pub file
 check_file_existence "/home/$USER/.ssh/id_rsa.pub"
@@ -128,7 +126,7 @@ if [[ $CONTINUE == "1" ]] ; then
   step_file=$LOG_DIR/${INSTANCE_NAME}-last-successful-step
   #Continue only if file exists
   if [[ ! -f $step_file ]]; then
-    echo "No last successful step, cannot resume. Exiting"
+    echo "No last successful step file ${step_file}, cannot resume. Exiting"
     exit 1
   fi
 
@@ -139,11 +137,8 @@ else
   check_instance_limit
 fi
 
-
 #Create file to ensure continue works if run/build is aborted before 1st step completes
 touch $step_file
-
-DOCK_NAME="pg_dev_${BUILD_ID}:latest"
 INSTANCE_IP=$(get_instance_ip ${INSTANCE_NAME})
 
 printf "\n\n********* RUNID= ${SUUID} *********\n\n"
@@ -168,8 +163,8 @@ function run_test() {
 
   3)
     local key_file=$(mktemp $WORKSPACE/keys-XXXXX)
-    echo ${USER}:$(cat /home/${USER}/.ssh/id_rsa.pub) > $key_file
-    echo plumgrid:$(echo ${COMMON_KEY}) >> $key_file
+    echo plumgrid:$(cat /home/${USER}/.ssh/id_rsa.pub) > ${key_file}
+    echo plumgrid:$(echo ${COMMON_KEY}) >> ${key_file}
     echo "Creating the instance[$INSTANCE_NAME] in the cloud"
     tryexec exec_gcloud_cmd instances create "${INSTANCE_NAME}" -q\
       --machine-type "$MACHINE_TYPE" --network "$NETWORK" --maintenance-policy \
@@ -189,40 +184,17 @@ function run_test() {
     ;;
 
   5)
-    echo "starting the pgdev container ${DOCK_NAME}"
-    tryexec run_dock_container ${INSTANCE_IP} ${DOCK_NAME} "./local_docker_id" "./local_docker_ip"
+    check_ssh_server_status ${INSTANCE_IP}
+    if [[ $retval == 1 ]]; then
+      echo "SSH server is not running on cloud instance"
+      exit $retval
+    fi
+    tryexec run_cmd_gci ${INSTANCE_IP} "sudo ifconfig eth0 mtu 1400"
+    tryexec run_cmd_gci ${INSTANCE_IP} "DT=\$(ifconfig eth0 | grep 'inet addr' | cut -d: -f2|cut -d' ' -f 1); sudo bash -c 'echo \"'\$DT'  \`hostname\`\" >> /etc/hosts'"
     record_step $step $step_file
     ;;
 
   6)
-    echo "Copy build-instance key to pgdev container"
-    tryexec run_cmd_gci ${INSTANCE_IP} "rm -f ~/.ssh/id_rsa*"
-    tryexec run_cmd_gci ${INSTANCE_IP} "ssh-keygen -t rsa -N \"\" -f ~/.ssh/id_rsa"
-    tryexec run_cmd_gci ${INSTANCE_IP} "sudo su -c \"cat /home/${USER}/.ssh/id_rsa.pub >> \
-      /var/lib/docker/btrfs/subvolumes/\`cat local_docker_id\`/home/plumgrid/.ssh/authorized_keys\""
-    record_step $step $step_file
-    ;;
-
-  7)
-    echo "Copy local key to pgdev container"
-    tryexec scp -o UserKnownHostsFile=/dev/null -o CheckHostIP=no -o StrictHostKeyChecking=no ~/.ssh/id_rsa.pub ${USER}@${INSTANCE_IP}:./auth-key.pub
-    tryexec run_cmd_gci ${INSTANCE_IP} "sudo su -c \"cat /home/${USER}/auth-key.pub >> \
-      /var/lib/docker/btrfs/subvolumes/\`cat local_docker_id\`/home/plumgrid/.ssh/authorized_keys\""
-    record_step $step $step_file
-    ;;
-
-  8)
-    check_ssh_server_status ${INSTANCE_IP}
-    if [[ $retval == 1 ]]; then
-      run_cmd_gci ${INSTANCE_IP} "sudo docker ps"
-      echo "Dokcer stopped.. Please run aurora build with --continue to retry!!"
-      record_step 3 $step_file
-      exit $retval
-    fi
-
-    record_step $step $step_file
-    ;;
-  9)
     if [[ $LOCAL_CHANGES == 1 ]]; then
       tryexec push_local_changes ${INSTANCE_IP} ${COMMIT_ID} ${ALPS_PATH}
       tryexec make_install_alps ${INSTANCE_IP} "/tmp/make_install_alps.log"
@@ -230,9 +202,10 @@ function run_test() {
       record_step $step $step_file
     fi
     ;;
-  10)
+
+  7)
     # This is here only untill https://gerrit:8443/#/c/10751/ gets merged.
-    echo "Execute the pre run-automaton on docker container"
+    echo "Execute the pre run-automaton"
     local local_file=$(mktemp $WORKSPACE/container_preinit.sh-XXXXX)
     cat /dev/null > ${local_file}
     echo "#!/bin/bash" >> ${local_file}
@@ -248,49 +221,50 @@ function run_test() {
       echo "sudo mv /tmp/resolv.conf /etc/resolv.conf" >> ${local_file}
     fi
     file_name=/tmp/$(basename ${local_file})
-    tryexec upload_to_docker ${INSTANCE_IP}  ${local_file} ${file_name}
+    tryexec upload ${INSTANCE_IP}  ${local_file} ${file_name}
     rm ${local_file}
-    tryexec run_cmd_docker ${INSTANCE_IP} "/bin/bash ${file_name}"
+    tryexec run_cmd_gci ${INSTANCE_IP} "/bin/bash ${file_name}"
     record_step $step $step_file
     ;;
 
-  11)
+  8)
     if [[ $AUTOMATON_INIT == 1 ]]; then
-      echo "Execute the run-automaton script on docker container"
+      echo "Execute the run-automaton script on cloud instance"
       tryexec run_automaton_init ${INSTANCE_IP} "/tmp/automaton_init.log"
       record_step $step $step_file
     fi
     ;;
-  12)
+
+  9)
     if [[ $AUTOMATON_INIT == 1 ]]; then
       echo "Poll the automaton-init cmd (tailing \"/tmp/automaton_init.log\" for complete logs)"
       retryexec run_poll_cmd ${INSTANCE_IP} "run_automaton_init.sh" "/tmp/automaton_init.log" "1"
-      tryexec download_from_docker ${INSTANCE_IP} "/tmp/automaton_init.log" "${LOG_DIR}/automaton_init_${INSTANCE_NAME}.log"
+      tryexec download ${INSTANCE_IP} "/tmp/automaton_init.log" "${LOG_DIR}/automaton_init_${INSTANCE_NAME}.log"
       record_step $step $step_file
     fi
     ;;
 
-  13)
-    tryexec upload_to_docker ${INSTANCE_IP} ${TEST_SCRIPT} /tmp/user_test_script.sh
+  10)
+    tryexec upload ${INSTANCE_IP} ${TEST_SCRIPT} /tmp/user_test_script.sh
     # tryexec is not needed because test can fail as well
-    tryexec run_cmd_docker_bg ${INSTANCE_IP} "/bin/bash /tmp/user_test_script.sh" "/tmp/test.logs"
+    tryexec run_cmd_gci_bg ${INSTANCE_IP} "/bin/bash /tmp/user_test_script.sh" "/tmp/test.logs"
     record_step $step $step_file
     ;;
 
-  14)
+  11)
     echo "Poll the test logs (tailing \"/tmp/test.log\")"
     tryexec run_poll_cmd ${INSTANCE_IP} "/tmp/user_test_script.sh" "/tmp/test.logs" "0"
-    tryexec download_from_docker ${INSTANCE_IP} "/tmp/test.logs" "${LOG_DIR}/${INSTANCE_NAME}.log"
+    tryexec download ${INSTANCE_IP} "/tmp/test.logs" "${LOG_DIR}/${INSTANCE_NAME}.log"
     record_step $step $step_file
     ;;
 
-  15)
+  12)
     echo "Downloading logs in ${LOG_DIR} directory"
     tryexec get_latest_logs ${INSTANCE_IP} ${INSTANCE_NAME} ${LOG_DIR}
     record_step $step $step_file
     ;;
 
-  16)
+  13)
     echo "Shutting down the Instance ${INSTANCE_NAME}"
     tryexec exec_gcloud_cmd instances delete ${INSTANCE_NAME} --delete-disks all  -q
     rm $step_file
@@ -307,7 +281,7 @@ for MAJOR_STEP in $MAJOR_STEPS; do
   echo " ====== Starting STEP [$MAJOR_STEP] Number of Steps ::${MINOR_STEPS_ST[$MAJOR_STEP]} -> ${MINOR_STEPS_ED[$MAJOR_STEP]}  ======"
   run_start_time=$(date +%s)
   for MINOR_STEP in `seq ${MINOR_STEPS_ST[$MAJOR_STEP]} ${MINOR_STEPS_ED[$MAJOR_STEP]}`; do
-    echo "    === Starting STEP [$MAJOR_STEP][$MINOR_STEP] ==="
+    printf "\n  === Starting STEP [$MAJOR_STEP][$MINOR_STEP] === \n"
     case "$MAJOR_STEP" in
       run)
         start_time=$(date +%s)
