Fix for not doing pkill on ssh-agent as it might cause a race condidtion when multiple builds are being executed on jenkins
Change-Id: I1d013e3fe8f2ccef58e26e686c3401fae5723149
Signed-off-by: Sushil Kumar Singh <sushilks@plumgrid.com>

diff --git a/aurora/gc_helpers.sh.in b/aurora/gc_helpers.sh.in
--- a/aurora/gc_helpers.sh.in
+++ b/aurora/gc_helpers.sh.in
@@ -808,6 +808,8 @@ function retryexec() {
          exit 1
        fi
      fi
+     echo "Command $@ Failed on try $retry : Will try again, restarting ssh-agent befor retrying"
+     pkill "ssh-agent" || true
      sleep 0.5
   done
 }
