Added retries to gcloud list command, upload and download commands.
Added check to verify if the snapshot already exists before starting aurora build.

Added timeout value to infra-settings.conf

Ticket: [INFRA-873]
Change-Id: I29e3e3605022b801f78ae49280ccd3bfadca2265
Signed-off-by: Ali Rizwan <alir@plumgrid.com>

diff --git a/aurora/gc_helpers.sh.in b/aurora/gc_helpers.sh.in
--- a/aurora/gc_helpers.sh.in
+++ b/aurora/gc_helpers.sh.in
@@ -1,3 +1,4 @@
+
 #!/bin/bash -e
 export PATH=@CMAKE_BINARY_DIR@/:/opt/pg/scripts:$PATH
 source aurora_infra_settings.conf
@@ -184,7 +185,7 @@ function checkout_existing_commit() {
     make -j4 install
 DELIM__
 
-  tryexec upload ${INSTANCE_IP}  ${local_file} /tmp
+  retryexec upload ${INSTANCE_IP}  ${local_file} /tmp
   tryexec run_cmd_gci ${INSTANCE_IP} "mv /tmp/$file_name ${instance_file}"
   tryexec run_bg_cmd ${INSTANCE_IP} "${instance_file}" "/bin/bash ${instance_file}" "$LOG_FILE"
   rm ${local_file}
@@ -217,7 +218,7 @@ function get_build_info() {
   echo "JENKINS_BUILD_DESCRIPTION_TEXT: \${headrev_short} by \${headauthor}: \${logmsg}"
 DELIM__
 
-  tryexec upload ${INSTANCE_IP} ${local_file} /tmp
+  retryexec upload ${INSTANCE_IP} ${local_file} /tmp
   run_cmd_gci ${INSTANCE_IP} "/bin/bash /tmp/${file_name}"
   rm ${local_file}
 }
@@ -250,7 +251,7 @@ function get_latest_snapshot_id() {
   local success=0
   #Retry to be safe
   for i in `seq 1 5`;do
-    latest_ss=$(gcloud compute snapshots list --sort-by=~NAME --regexp=${PRIM_INST_NAME}-d1-.* --limit=1 | grep ${PRIM_INST_NAME}-d1- | cut  -d ' ' -f 1)
+    latest_ss=$(timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute snapshots list --sort-by=~NAME --regexp=${PRIM_INST_NAME}-d1-.* --limit=1 | grep ${PRIM_INST_NAME}-d1- | cut  -d ' ' -f 1)
     ssid="${latest_ss##*-}"
 	#Break if non empty
     if [[ -n $ssid ]]; then
@@ -327,16 +328,16 @@ function get_instance_ip() {
   local success=0
   #Retry to be safe
   for i in `seq 1 5`; do
-    internal_ip=$(gcloud compute instances list ${INSTANCE_NAME} --zones=${ZONE} | grep ${INSTANCE_NAME})
+    internal_ip=$(timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute instances list ${INSTANCE_NAME} --zones=${ZONE} | grep ${INSTANCE_NAME} || true)
     internal_ip=$(echo "$internal_ip" | awk '{ print $4}')
     #Break if non-empty
-    if [[ -n $internal_ip ]];then
+    if [[ -n "$internal_ip" ]];then
       success=1
       break
     fi
   done
   #Exit if retries failed
-  if [[ $success -eq 0 ]]; then
+  if [[ "$success" -eq 0 ]]; then
     echo "Instance IP not found. Please check if the instance $INSTANCE_NAME is running. Exiting."  >&2
     exit 1
   fi
@@ -403,13 +404,13 @@ function get_latest_logs() {
   echo "tar -zcf /tmp/\${LOG_FNAME}.tar \`cat /tmp/latest_log_dir\`" >> ${local_file}
   echo "echo \${LOG_FNAME} > /tmp/latest_log_filename"  >> ${local_file}
   local file_name=/tmp/$(basename ${local_file})
-  upload ${instance_ip} ${local_file} ${file_name}
+  retryexec upload ${instance_ip} ${local_file} ${file_name}
   rm ${local_file}
   run_cmd_gci ${instance_ip} "bash ${file_name}"
   local log_filename=$(mktemp ${dest_dir}/latest_log_filename-XXXXX)
-  download ${instance_ip} /tmp/latest_log_filename ${log_filename}
+  retryexec download ${instance_ip} /tmp/latest_log_filename ${log_filename}
   local log_tar=$(cat ${log_filename})
-  download ${instance_ip} /tmp/${log_tar}.tar ${dest_dir}/${instance_name}-logs.tar
+  retryexec download ${instance_ip} /tmp/${log_tar}.tar ${dest_dir}/${instance_name}-logs.tar
   echo "Logs have been placed at ${dest_dir}/${instance_name}-logs.tar"
   rm ${log_filename}
 }
@@ -455,7 +456,7 @@ DELIM__
     echo "echo \"$process completely successfully, exiting\"" >> ${local_file}
   fi
   local instance_file=/tmp/$(basename ${local_file})
-  tryexec upload ${INSTANCE_IP} ${local_file} ${instance_file}
+  retryexec upload ${INSTANCE_IP} ${local_file} ${instance_file}
   rm ${local_file}
   retryexec run_cmd_gci ${INSTANCE_IP} "bash ${instance_file}"
 }
@@ -503,7 +504,7 @@ function make_install_alps() {
   #File name needs to be constant for continue functionality, thus renaming.
   local instance_file=/tmp/$(basename $local_file)
   local renamed_file=/tmp/make_install_alps.sh
-  tryexec upload ${INSTANCE_IP} ${local_file} ${instance_file}
+  retryexec upload ${INSTANCE_IP} ${local_file} ${instance_file}
   tryexec run_cmd_gci ${INSTANCE_IP} "mv ${instance_file} ${renamed_file}"
   rm ${local_file}
   tryexec run_bg_cmd ${INSTANCE_IP} "${renamed_file}" "/bin/bash ${renamed_file}" "$LOG_FILE"
@@ -536,7 +537,7 @@ DELIM__
   #File name needs to be constant for continue functionality, thus renaming.
   local instance_file=/tmp/$(basename ${local_file})
   local renamed_file=/tmp/make_tools_iovisor.sh
-  tryexec upload ${INSTANCE_IP}  ${local_file} ${instance_file}
+  retryexec upload ${INSTANCE_IP}  ${local_file} ${instance_file}
   tryexec run_cmd_gci ${INSTANCE_IP} "mv ${instance_file} ${renamed_file}"
   rm ${local_file}
   tryexec run_bg_cmd ${INSTANCE_IP} "${renamed_file}" "/bin/bash ${renamed_file}" "$LOG_FILE"
@@ -568,7 +569,7 @@ DELIM__
   #File name needs to be constant for continue functionality, thus renaming.
   local instance_file=/tmp/$(basename ${local_file})
   local renamed_file=/tmp/check_elfsurgeon.sh
-  tryexec upload ${INSTANCE_IP}  ${local_file} ${instance_file}
+  retryexec upload ${INSTANCE_IP}  ${local_file} ${instance_file}
   tryexec run_cmd_gci ${INSTANCE_IP} "mv ${instance_file} ${renamed_file}"
   rm ${local_file}
   tryexec run_bg_cmd ${INSTANCE_IP} "${renamed_file}" "/bin/bash ${renamed_file}" "$LOG_FILE"
@@ -587,7 +588,7 @@ function exec_gcloud_instances() {
   case $operation in
     create)
       # Check if the instance already exists
-      timeout -k 5 120 gcloud compute instances list ${name} --zones $ZONE | grep -q "${name}" || retval=$?
+      timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute instances list ${name} --zones $ZONE | grep -q "${name}" || retval=$?
       if [ $retval -eq 0 ]; then
         echo "Instance:$name already exists."
         return 1
@@ -595,7 +596,7 @@ function exec_gcloud_instances() {
       ;;
     delete)
         # Check if the instance is already deleted
-        timeout -k 5 120 gcloud compute instances list ${name} --zones $ZONE | grep -q "${name}" || retval=$?
+        timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute instances list ${name} --zones $ZONE | grep -q "${name}" || retval=$?
         if [ $retval -ne 0 ]; then
           echo "Instance:$name does not exist."
           return 1
@@ -611,7 +612,7 @@ function exec_gcloud_instances() {
     echo "Try-$i: gcloud compute instances $operation $name $options"
     # Execute the command.
     retval=0
-    timeout -k 5 360 gcloud compute instances $operation $name $options || retval=$?
+    timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute instances $operation $name $options || retval=$?
     if [ $retval -eq 0 ]; then
       return 0;
     fi
@@ -621,14 +622,14 @@ function exec_gcloud_instances() {
       retval=0
       case $operation in
         create)
-          timeout -k 5 120 gcloud compute instances list $name | grep "${name}" | grep "RUNNING" || retval=$?
+          timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute instances list $name | grep "${name}" | grep "RUNNING" || retval=$?
           if [ $retval -eq 0 ]; then
             success=1
             break
           fi
           ;;
         delete)
-          timeout -k 5 120 gcloud compute instances list $name | grep "${name}" || retval=$?
+          timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute instances list $name | grep "${name}" || retval=$?
           if [ $retval -ne 0 ]; then
             success=1
             break
@@ -657,7 +658,7 @@ function exec_gcloud_snapshots() {
   case $operation in
   delete)
     # Check if the snapshot is already deleted
-    timeout -k 5 120 gcloud compute snapshots list ${name} | grep -q "${name}" || retval=$?
+    timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute snapshots list ${name} | grep -q "${name}" || retval=$?
     if [ $retval -ne 0 ]; then
       echo "Snapshot:$name does not exist."
       return 1
@@ -673,7 +674,7 @@ function exec_gcloud_snapshots() {
     echo "Try-$i: gcloud compute snapshot $operation $name $options"
     # Execute the command.
     retval=0
-    timeout -k 5 360 gcloud compute snapshots $operation $name $options || retval=$?
+    timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute snapshots $operation $name $options || retval=$?
     if [ $retval -eq 0 ]; then
       return 0;
     fi
@@ -683,7 +684,7 @@ function exec_gcloud_snapshots() {
       echo "$j: Checking if $operation snapshots:$name succeeded"
       retval=0
 
-      timeout -k 5 120 gcloud compute snapshots list $name | grep "${name}" || retval=$?
+      timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute snapshots list $name | grep "${name}" || retval=$?
       if [ $retval -ne 0 ]; then
         success=1
         break
@@ -710,7 +711,7 @@ function exec_gcloud_disks() {
   case $operation in
     create)
       # Check if disk already exists
-      timeout -k 5 120 gcloud compute disks list ${name} --zones $ZONE | grep -q "${name}" || retval=$?
+      timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute disks list ${name} --zones $ZONE | grep -q "${name}" || retval=$?
       if [ $retval -eq 0 ]; then
         echo "Disk:$name already exists."
         return 1
@@ -718,7 +719,7 @@ function exec_gcloud_disks() {
       ;;
     delete)
       # Check if disk already deleted
-      timeout -k 5 120 gcloud compute disks list ${name} --zones $ZONE | grep -q "${name}" || retval=$?
+      timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute disks list ${name} --zones $ZONE | grep -q "${name}" || retval=$?
       if [ $retval -ne 0 ]; then
         echo "Disk:$name does not exist."
         return 1
@@ -727,7 +728,7 @@ function exec_gcloud_disks() {
     snapshot)
       local snapshot_name=$4
       # Check if disk already deleted
-      timeout -k 5 120 gcloud compute snapshots list ${snapshot_name} | grep -q "${snapshot_name}" || retval=$?
+      timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute snapshots list ${snapshot_name} | grep -q "${snapshot_name}" || retval=$?
       if [ $retval -eq 0 ]; then
         echo "Snapshot:$snapshot_name already exists."
         return 1
@@ -743,7 +744,7 @@ function exec_gcloud_disks() {
     echo "Try-$i: gcloud compute disks $operation $name $options"
     # Execute the command.
     retval=0
-    timeout -k 5 360 gcloud compute disks $operation $name $options || retval=$?
+    timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute disks $operation $name $options || retval=$?
     if [ $retval -eq 0 ]; then
       return 0;
     fi
@@ -754,21 +755,21 @@ function exec_gcloud_disks() {
       retval=0
       case $operation in
         create)
-          timeout -k 5 120 gcloud compute disks list $name | grep "${name}" | grep "READY" || retval=$?
+          timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute disks list $name | grep "${name}" | grep "READY" || retval=$?
           if [ $retval -eq 0 ]; then
             success=1
             break
           fi
           ;;
         delete)
-          timeout -k 5 120 gcloud compute disks list $name | grep "${name}" || retval=$?
+          timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute disks list $name | grep "${name}" || retval=$?
           if [ $retval -ne 0 ]; then
             success=1
             break
           fi
           ;;
         snapshot)
-          timeout -k 5 120 gcloud compute snapshots list $snapshot_name | grep "${snapshot_name}" | grep "READY" || retval=$?
+          timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute snapshots list $snapshot_name | grep "${snapshot_name}" | grep "READY" || retval=$?
           if [ $retval -eq 0 ]; then
             success=1
             break
@@ -958,12 +959,40 @@ function check_build_inputs() {
   fi
   #Check if branch exists
   git ls-remote ssh://${gerritid}@${GERRIT_IP}:${GERRIT_PORT}/${PROJECT} "${BRANCH}" | grep -q "${BRANCH}" || RESULT=$?
-    if [[ $RESULT -ne 0 ]];then
+  if [[ $RESULT -ne 0 ]];then
     echo "Branch: $BRANCH does not exist for the project: ${PROJECT}"
     show_build_help
     exit 1
   fi
 }
+
+# *****************************************************************************
+# Function: check_snapshot_exists
+# Purpose : Checks if the given snapshot exists and is in the READY state
+# Usage   : check_snapshot_exists <snapshot name> <retries>
+# Prereq  :
+# *****************************************************************************
+function check_snapshot_exists() {
+  local snapshot_name=$1
+  local retries=${2:-5}
+  local success=0
+  #Check the second disk, Retry to be safe
+  for i in `seq 1 $retries`; do
+    local snapshot=$(timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute snapshots list ${snapshot_name} | grep "${snapshot_name}")
+    local snapshot_state=$(echo "$snapshot" | awk '{ print $4}')
+    #Break loop if snapshot exists and is READY
+    if [[ $snapshot_state == "READY" ]];then
+      success=1
+      break
+    fi
+  done
+  #Return failure if not found.
+  if [[ $success -ne 1 ]]; then
+    return 1
+  fi
+
+}
+
 # *****************************************************************************
 # Function: check_run_inputs
 # Purpose : Checks if the inputs provided to aurora run are correct.
@@ -972,19 +1001,13 @@ function check_build_inputs() {
 # *****************************************************************************
 function check_run_inputs() {
   local BUILDID=$1
-  local RESULT
+  local success=0
+  #Check the second disk, Retry to be safe
+  check_snapshot_exists "${BUILDID}-ssd1" || success=1
+  check_snapshot_exists "${BUILDID}-ssd2" || success=1
 
-  gcloud compute snapshots list ${BUILDID}-ssd1 | grep "${BUILDID}-ssd1" || RESULT=$?
-  if [[ $RESULT -ne 0 ]];then
-    echo "Snapshot ${BUILDID}-ssd1 does not exist, wrong Build-ID"
-    show_run_help
-    exit 1
-  fi
-
-  gcloud compute snapshots list ${BUILDID}-ssd2 | grep "${BUILDID}-ssd2" || RESULT=$?
-  if [[ $RESULT -ne 0 ]];then
-    echo "Snapshot ${BUILDID}-ssd2 does not exist, wrong Build-ID"
-    show_run_help
+  if [[ "$success" -eq 1 ]]; then
+    echo "Build-Id: ${BUILDID} not found, exiting"
     exit 1
   fi
 }
@@ -1035,7 +1058,7 @@ function download() {
 # Prereq  : aurora init has been called
 # *****************************************************************************
 function check_instance_limit() {
-  local CURRENT_INSTANCES=$(gcloud compute instances list --regexp "${emailid}-.*" --zones $ZONE | grep "${emailid}-" | wc -l)
+  local CURRENT_INSTANCES=$(timeout -k 5 ${GCLOUD_CMD_TIMEOUT} gcloud compute instances list --regexp "${emailid}-.*" --zones $ZONE | grep "${emailid}-" | wc -l)
   #Check against max instances allowed.
   if [[ $CURRENT_INSTANCES -lt $MAX_USER_INSTANCES ]]; then
     return 0
