Adding error message if Primary Snapshot is not available while running aurora build.
Signed-off-by: hashaamt <hashaamt@plumgrid.com>
[INFRA-714]
Change-Id: Ie3fdb33d9298af9a46cddcbb1e037bf3be219089
Signed-off-by: hashaamt <hashaamt@plumgrid.com>

diff --git a/aurora/gc_helpers.sh.in b/aurora/gc_helpers.sh.in
--- a/aurora/gc_helpers.sh.in
+++ b/aurora/gc_helpers.sh.in
@@ -251,6 +251,7 @@ function get_latest_snapshot_id() {
   done
   #Exit if retries failed.
   if [[ $success -eq 0 ]]; then
+    echo "Snapshot not found. Exiting" >&2
     return 1
   fi
 
