[INFRA-697] : Jenkins/gcloud: elfsurgeon files are not checked at the end of the build
Patch #2: Addressing Marco and Tahir's comments.

Change-Id: I8851b6763b0e8a1e9a483a836084653a87abae0b
Ticket: [INFRA-697]
Signed-off-by: Irfan Ali Shah <irfans@plumgrid.com>

diff --git a/aurora/gc_helpers.sh.in b/aurora/gc_helpers.sh.in
--- a/aurora/gc_helpers.sh.in
+++ b/aurora/gc_helpers.sh.in
@@ -389,6 +389,35 @@ function run_build_all() {
   tryexec run_bg_cmd ${INSTANCE_IP} "${renamed_file}" "/bin/bash ${renamed_file}" "$LOG_FILE"
 }
 # ******************************************************************************
+# Function: check_elfsurgeon
+# Purpose : Creates a script which makes alps, checks the elfsurgeon files, uploads
+#           and runs the script.The return value for the script is echoed to
+#           check for failure.
+# Usage   : check_elfsurgeon <cloud_instance_ip> <log file>
+# ******************************************************************************
+function check_elfsurgeon() {
+  local INSTANCE_IP=$1
+  local LOG_FILE=$2
+  local local_file=$(mktemp $WORKSPACE/check_elfsurgeon-XXXXX)
+  cat /dev/null > ${local_file}
+  cat >> ${local_file} <<DELIM__
+cd /home/plumgrid/work/alps/build
+make -j4
+elfsurgeon_files=\$(git status --porcelain | grep 'common/elfsurgeon/dependency_hist' | wc -l)
+if [[ "\$elfsurgeon_files" != "0" ]]; then
+git status --porcelain | grep 'common/elfsurgeon/dependency_hist'
+echo "\${elfsurgeon_files} ELFsurgeon history files were not updated:"
+exit 1; fi
+DELIM__
+  #File name needs to be constant for continue functionality, thus renaming.
+  local instance_file=/tmp/$(basename ${local_file})
+  local renamed_file=/tmp/check_elfsurgeon.sh
+  tryexec upload ${INSTANCE_IP}  ${local_file} ${instance_file}
+  tryexec run_cmd_gci ${INSTANCE_IP} "mv ${instance_file} ${renamed_file}"
+  rm ${local_file}
+  tryexec run_bg_cmd ${INSTANCE_IP} "${renamed_file}" "/bin/bash ${renamed_file}" "$LOG_FILE"
+}
+# ******************************************************************************
 # Function: run_automaton_init
 # Purpose : Creates a script for running automaton-init, uploads and runs the script.
 #           The return value for automaton-init is echoed to
