Preemptible instances for aurora.
Change-Id: If87840c0b17b2291b2f17eac320561992c43c180
Ticket: none
Signed-off-by: Ali Rizwan <alir@plumgrid.com>

diff --git a/aurora/pipeline_scripts/alps/alps_run_pipelines.sh.in b/aurora/pipeline_scripts/alps/alps_run_pipelines.sh.in
--- a/aurora/pipeline_scripts/alps/alps_run_pipelines.sh.in
+++ b/aurora/pipeline_scripts/alps/alps_run_pipelines.sh.in
@@ -11,6 +11,7 @@ source pl_utils.sh
 source pl_help.sh
 source pl_settings.conf
 source gc_helpers.sh
+source aurora_utils.sh
 
 #Kill child  processes, if some exist, before exiting.
 function exit_handler() {
@@ -26,13 +27,13 @@ if [[ $3 == "help" ]]; then
 fi
 BUILD_ENV_USER=${USER}
 STEP_ST=1
-STEP_ED=7
+STEP_ED=9
 DEST_SCRIPT_DIR=0
 
 echo "run_pipelines.sh $@"
 ARGS=$@
 # read the options
-TEMP=`getopt -o Q:R:E:W:l:P:b:i:f:t:u:s:n:\r:d:IFKc:e:a:h --long major:,minor_start:,minor_end:,WORKSPACE:,buildid:,pipeline:,branch:,test_iterations:,first_test:,step_size:,update_db_failure_limit:,script:,num_instances:,base_script_dir:,dest_script_dir:,initial_run,db_update,keep-running,local_commit:,existing_commit_hash:,alps-path:,cost_pipeline_code:,\help -n 'run_all_test.sh' -- "$@"`
+TEMP=`getopt -o Q:R:E:W:l:P:b:i:f:t:u:s:n:\r:d:IFKc:e:a:h --long major:,preemptible,minor_start:,minor_end:,WORKSPACE:,buildid:,pipeline:,branch:,test_iterations:,first_test:,step_size:,update_db_failure_limit:,script:,num_instances:,base_script_dir:,dest_script_dir:,initial_run,db_update,keep-running,local_commit:,existing_commit_hash:,alps-path:,cost_pipeline_code:,\help -n 'run_all_test.sh' -- "$@"`
 eval set -- "$TEMP"
 
 # extract options and their arguments into variables.
@@ -56,6 +57,7 @@ while true ; do
     -I|--initial_run) INITIAL_RUN="true" ; shift ;;
     -F|--db_update) DB_UPDATE="true" ; shift ;;
     -K|--keep-running) KEEP_RUNNING="-K"; shift ;;
+    --preemptible) PREEMPTIBLE="--preemptible" ; shift ;;
     #Optional argments for local changes transfer
     -c|--local_commit) LOCAL_COMMIT_HASH="-c $2" ; shift 2 ;;
     -e|--existing_commit_hash) EXISTING_COMMIT_HASH=$2 ; shift 2 ;;
@@ -128,34 +130,40 @@ function run_test() {
     pids=()
     echo "log_dir=$log_dir script_dir=$script_dir"
     while read -r -d $'\0'; do
-      aurora run -l ${USER_BUILD_ID} -o ${log_dir} -s $REPLY -e $EXISTING_COMMIT_HASH --cost_pipeline_code $COST_PIPELINE_CODE $KEEP_RUNNING $LOCAL_COMMIT_HASH $ALPS_PATH > $REPLY.txt 2>&1 &
+      aurora run -l ${USER_BUILD_ID} -o ${log_dir} -s $REPLY -e $EXISTING_COMMIT_HASH --cost_pipeline_code $COST_PIPELINE_CODE $KEEP_RUNNING $LOCAL_COMMIT_HASH $ALPS_PATH $PREEMPTIBLE > $REPLY.txt 2>&1 &
       #Get the pid of the last background command
       pids+=("$!")
     done < <(find ${script_dir} -regextype posix-extended  -regex '^.*.sh-[0-9]+$' -print0)
-    sleep 30
+    sleep 2
     ;;
 
   3)
-    pipeline_start_time=$(date +%s)
     echo "Waiting for command to finish ..."
-    # Background loop to print the number of aurora_run processes
-    while [[ ! -z `pgrep -f "run -l ${USER_BUILD_ID} -o ${log_dir}"` ]]; do
-      echo -n "[`pgrep -f \"run -l ${USER_BUILD_ID} -o ${log_dir}\" | wc -l`] ";
-      sleep 60 ;
-    done &
-    echoer_pid=$!
+    echoer_pid=$(print_background_jobs ${USER_BUILD_ID} ${log_dir})
+    pipeline_start_time=$(date +%s)
+
     FAIL=0
     for pid in "${pids[@]}"; do
       wait "$pid" || FAIL=$(($? + $FAIL))
     done
+
     pipeline_end_time=$(date +%s)
+
+    if [[ -n "$PREEMPTIBLE" ]]; then
+      mkdir -p ${script_dir}/preempted_instances
+    fi
+
     #Exit if any value is nonzero
     if [[ $FAIL != 0 ]]; then
       #Kill the echo while loop, suppress output
       disown $echoer_pid && kill $echoer_pid
       #Copy the aurora_run logs.
       for file in `ls ${script_dir}/*.txt` ; do
-        grep "Run has been completed successfully" $file > /dev/null || cp $file "$WORKSPACE/logs/AURORA.RUN.FAILED.`basename ${file}`"
+        if [[ ! `grep "Run has been completed successfully" $file > /dev/null` ]]; then
+          script_name=$(basename ${file})
+          script_name=$(echo $script_name | sed 's/.txt//')
+          cp ${script_dir}/$script_name ${script_dir}/preempted_instances
+        fi
       done
       echo "Some aurora runs exited unsuccesfully."
       status=1
@@ -165,14 +173,62 @@ function run_test() {
       echo "Aurora run completed successfully."
     fi
     ;;
-
   4)
+    #Get a list of instances that have been preempted
+    RUN_ID=$(echo $USER_BUILD_ID | sed 's/bld/run/')
+    delete_instances "$RUN_ID" "-f"
+    #If status is 1 and preemtible switch is present then check and retry the failing instances
+    if [[ "$status" == 1 && -n "$PREEMPTIBLE" ]]; then
+      pids=()
+      echo "log_dir=$log_dir script_dir=$script_dir"
+      while read -r -d $'\0'; do
+        aurora run -l ${USER_BUILD_ID} -o ${log_dir} -s $REPLY -e $EXISTING_COMMIT_HASH --cost_pipeline_code $COST_PIPELINE_CODE $KEEP_RUNNING $LOCAL_COMMIT_HASH $ALPS_PATH > $REPLY.txt 2>&1 &
+        #Get the pid of the last background command
+        pids+=("$!")
+      done < <(find ${script_dir}/preempted_instances -regextype posix-extended  -regex '^.*.sh-[0-9]+$' -print0)
+      sleep 30
+    fi
+    ;;
+
+  5)
+    #If status is 1 and preemtible switch is present then check and retry the failing instances
+    if [[ "$status" == 1 && -n "$PREEMPTIBLE" ]]; then
+      echo "Waiting for command to finish ..."
+
+      echoer_pid=$(print_background_jobs ${USER_BUILD_ID} ${log_dir})
+
+      FAIL=0
+      for pid in "${pids[@]}"; do
+        wait "$pid" || FAIL=$(($? + $FAIL))
+      done
+
+      #Exit if any value is nonzero
+      if [[ $FAIL != 0 ]]; then
+        #Kill the echo while loop, suppress output
+        disown $echoer_pid && kill $echoer_pid
+        #Copy the aurora_run logs.
+        for file in `ls ${script_dir}/*.txt` ; do
+          if [[ ! `grep "Run has been completed successfully" $file > /dev/null` ]]; then
+            cp $file "$WORKSPACE/logs/AURORA.RUN.FAILED.`basename ${file}`"
+          fi
+        done
+        echo "Some aurora runs exited unsuccesfully."
+        status=1
+      else
+        #Kill the echo while loop, suppress output
+        disown $echoer_pid && kill $echoer_pid
+        echo "Aurora run completed successfully."
+        status=0
+      fi
+    fi
+    ;;
+  6)
     # Start collecting logs
     echo "Copying all logs to ${WORKSPACE}/logs directory"
     find ${log_dir} -name "*${MOD_BUILD_ID}*.tar" -type f -exec tar xf {} -C ${untar_log_dir} \; -exec rm {} \;
     ;;
 
-  5)
+  7)
     # Generate failed test case report.
     num_failures=$(get_failing_test_number ${untar_log_dir})
     echo "num_failures=$num_failures"
@@ -191,7 +247,7 @@ function run_test() {
     generate_failing_list "${untar_log_dir}" "${WORKSPACE}/logs/failing-list.log"
     ;;
 
-  6)
+  8)
     generate_ctest_output ${untar_log_dir} ${WORKSPACE}/logs/ctest_output.log
     if [[ -e ${WORKSPACE}/logs/ctest_output.log ]]; then
       pushd ${WORKSPACE}/logs
@@ -199,7 +255,8 @@ function run_test() {
       popd
     fi
     ;;
-  7)
+
+  9)
     #Collect XML logs
     if [[ "$PIPELINE" == "omni" || "$PIPELINE" == "extended" || "$PIPELINE" == "smoke" || "$PIPELINE" == "unstable" ]]; then
         collect_xml_logs "${untar_log_dir}" "${WORKSPACE}/logs/xml_logs/"
