Revert "Moved mark as unstable functionality to builder."
This reverts commit 5d3349816fe394553ed6ce7ecf1f7d1b90ca4931.
Need to wait until the correspoding bulder commit gets merged.
https://gerrit:8443/#/c/13012/2

Change-Id: I20250f0db5748a563acb045af1cb1c501ee5e0c7
Signed-off-by: Ali Rizwan <alir@plumgrid.com>

diff --git a/aurora/pipeline_scripts/alps/flag_failing_tests.sh.in b/aurora/pipeline_scripts/alps/flag_failing_tests.sh.in
--- a/aurora/pipeline_scripts/alps/flag_failing_tests.sh.in
+++ b/aurora/pipeline_scripts/alps/flag_failing_tests.sh.in
@@ -10,16 +10,18 @@ if [[ $1 == "help" ]]; then
   exit 1
 fi
 
-TEMP=`getopt -o l:p:W:Ki:b:n:D:R:E:\h --long buildid:,pl_failing_tests_list:,WORKSPACE:,branch:,keep-running,test_iterations:,num_instances:,db:,minor_st:,minor_end:,\help -n 'aurora.sh' -- "$@"`
+TEMP=`getopt -o l:p:W:Ki:a:b:n:D:R:E:\h --long buildid:,alps-path:,pl_failing_tests_list:,WORKSPACE:,branch:,keep-running,test_iterations:,num_instances:,db:,minor_st:,minor_end:,\help -n 'aurora.sh' -- "$@"`
 eval set -- "$TEMP"
 
 STEP_ST=1
 STEP_ED=7
 
+alps_path=/home/${USER}/work/alps
 
 while true ; do
   case "$1" in
     -l|--buildid) BUILD_ID=$2 ; shift 2 ;;
+    -a|--alps-path) alps_path=$2 ; shift 2 ;;
     -p|--pl_failing_tests_list) PL_FAILING_TESTS_LIST=$2 ; shift 2 ;;
     -W| --WORKSPACE) export WORKSPACE=$2 ; shift 2 ;;
     -K|--keep-running) KEEP_RUNNING="-K" ; shift ;;
@@ -38,7 +40,7 @@ while true ; do
 done
 
 #Verify inputs
-check_flag_inputs $BUILD_ID $PL_FAILING_TESTS_LIST $FLAG_TEST_ITERATIONS $FLAG_NUM_INSTANCES $BRANCH
+check_flag_inputs $BUILD_ID $PL_FAILING_TESTS_LIST $FLAG_TEST_ITERATIONS $FLAG_NUM_INSTANCES $BRANCH $alps_path
 
 if [[ ! -d ${WORKSPACE}/flag ]]; then
   mkdir -p ${WORKSPACE}/flag
@@ -117,7 +119,7 @@ function flag_failing_tests() {
     ;;
 
   7)
-    echo "Generate output file."
+    echo "Mark test cases as unstable"
     i=1
     echo "Generate a list of all failing test cases in database"
     sqlite3 $FAILING_TESTS_DB "select NAME FROM $FAILING_TESTS_TABLE;" > ${all_failing_tests_list}
@@ -132,14 +134,28 @@ function flag_failing_tests() {
       failing_since=$((now-first_occurence))
       limit=$(($MARK_UNSTABLE_AFTER_DAYS*86400))
 
+      echo "Finding CMakeLists.txt file for test:$test_name"
+      test_cmake_file=$(grep --include=CMakeLists.txt -rwl "$alps_path" -e "$test_name" || true )
+      #Skip test if file not found
+      if [[ -z "$test_cmake_file" ]]; then
+        echo "CMakeLists.txt file for test:$test_name not found, skipping test."
+        continue
+      else
+        echo "Path to CMake file for test:$test_name $test_cmake_file"
+      fi
+      #Get the primary owner for the test
+      test_primary_owner=$(get_test_owner_name $test_cmake_file)
+      echo "Owner for test:$test_name, $test_primary_owner"
+      #Mark test as unstable if failing for more than the threshold
       if [[ $failure_prob -ge 10 && ${failing_since} -gt ${limit} ]]; then
+          echo "Marking test case: $test_name as unstable"
+          mark_test_unstable $test_name $failure_prob $test_cmake_file $BRANCH $alps_path
           #Remove the test from the database
-          echo "Test:$test_name Status:unstable "
           remove_test_from_db $FAILING_TESTS_DB $test_name
           #Send status to builder if test is marked unstable
           test_status="unstable"
       fi
-      echo "$test_name,$failure_prob,$failing_since,$BRANCH,$test_status" >> ${test_status_file}
+      echo "$test_name,$failure_prob,$failing_since,$BRANCH,$test_status,$test_primary_owner" >> ${test_status_file}
       i=$((i+1))
     done < ${all_failing_tests_list}
     ;;
diff --git a/aurora/pipeline_scripts/alps/pl_utils.sh.in b/aurora/pipeline_scripts/alps/pl_utils.sh.in
--- a/aurora/pipeline_scripts/alps/pl_utils.sh.in
+++ b/aurora/pipeline_scripts/alps/pl_utils.sh.in
@@ -92,6 +92,44 @@ function update_failing_tests_prob() {
   fi
 }
 
+# *****************************************************************************
+# Function: mark_test_unstable
+# Purpose : Marks a test as unstable on a given branch. Creates and pushes a commit.
+# Usage   : mark_test_unstable <test_name> <probability of failure> <CMakeLists.txt file path>
+#           <branch> <path to alps>
+# *****************************************************************************
+function mark_test_unstable() {
+  local test_name=$1
+  local failure_prob=$2
+  local file_name=$3
+  local branch=$4
+  local alps_path=$5
+  #Checkout Branch
+  git --git-dir=${alps_path}/.git --work-tree=${alps_path} reset --hard origin/$branch
+  git --git-dir=${alps_path}/.git --work-tree=${alps_path} checkout $branch
+  #Reset and update
+  git --git-dir=${alps_path}/.git --work-tree=${alps_path} reset --hard origin/$branch
+  git --git-dir=${alps_path}/.git --work-tree=${alps_path} pull --rebase
+  #Get CMakeLists.txt file name
+  echo "Test:$test_name found in: $file_name"
+  #Mark as unstable
+  #Some tests don't have a 'NAME' tag in the CMakeLists.txt. This regex replaces the test name with <$test_name UNSTABLE>
+  sed -i -E "s/_test\ *\(\ *(NAME\ +$test_name|$test_name)/_test\(NAME $test_name UNSTABLE/" $file_name
+  #Create the commit message
+  local commit_message=$(mktemp /tmp/commit-message-XXXXX.txt)
+  #TODO: Need a better commit message.
+  echo "Marking Test:$test_name as UNSTABLE" >> $commit_message
+  echo "$test_name is failing at:${BUILD_URL} with $failure_prob% probability." >> $commit_message
+
+  #Add the file to patch and commit
+  git --git-dir=${alps_path}/.git --work-tree=${alps_path} commit -s -o -F $commit_message $file_name
+  #push the commit for review
+  git --git-dir=${alps_path}/.git --work-tree=${alps_path} push origin HEAD:refs/for/$branch
+  #use this if we want to bypass code review
+  #git push origin HEAD:refs/heads/$branch
+  #Delete the commit message
+  rm ${commit_message}
+}
 
 # *****************************************************************************
 # Function: check_flag_inputs
@@ -135,6 +173,29 @@ function check_flag_inputs() {
     exit 1
   fi
 
+  #Verify alps exists at specified path
+  git rev-parse --resolve-git-dir $alps_path/.git || RESULT=$?
+  if [[ $RESULT != "0" ]]; then
+    echo "Alps not found at :$ALPS_PATH"
+    echo "Use the -a(--alps-path) to specify the path to alps"
+    exit 1
+  fi
 
-
+}
+# *****************************************************************************
+# Function: get_test_owner_name
+# Purpose : Returns the owner name from a given CMakeLists.txt file
+# Usage   : get_test_owner_name <path to cmakelists.txt file>
+# *****************************************************************************
+function get_test_owner_name() {
+  local test_cmake_file=$1
+  local test_folder=$(dirname $test_cmake_file)
+  local test_owner_file=$test_folder/OWNERS
+    #If owner file is not found , go one level up and try again
+    while [[ ! -f $test_owner_file && $test_folder != $alps_path ]]; do
+      test_folder=$(dirname $test_folder)
+      test_owner_file=$test_folder/OWNERS
+    done
+  local test_primary_owner=$(grep - $test_owner_file | cut -d ' ' -f 2 | head -1)
+  echo "$test_primary_owner"
 }
