Minor fixes for the pgui-smoke
Ticket: none
Change-Id: I8019d8c6b10ee0f992064f430717badc4ef927b4
Signed-off-by: Muaaz Saleem <muaazs@plumgrid.com>

diff --git a/aurora/pipeline_scripts/alps/pgui_base_test.sh.in b/aurora/pipeline_scripts/alps/pgui_base_test.sh.in
--- a/aurora/pipeline_scripts/alps/pgui_base_test.sh.in
+++ b/aurora/pipeline_scripts/alps/pgui_base_test.sh.in
@@ -5,9 +5,9 @@
 
 instance_no="1"
 PIPELINE="smoke"
-export EXPORT_FAILURES_DIR="/tmp/aurora_logs/$instance_no"
-export EXPORT_FAILURES_DIR_TMP="/tmp/log/$instance_no"
-export PATH="$PATH:/opt/pg/scripts/:/home/plumgrid/work/pg_ui/devtools/node_modules/grunt-cli/bin"
+export EXPORT_FAILURES_DIR="/tmp/aurora_logs/${instance_no}"
+export EXPORT_FAILURES_DIR_TMP="/tmp/log/${instance_no}"
+export PATH="${PATH}:/opt/pg/scripts/:/home/plumgrid/work/pg_ui/devtools/node_modules/grunt-cli/bin"
 rm -rf "${EXPORT_FAILURES_DIR}"
 rm -rf "${EXPORT_FAILURES_DIR_TMP}"
 mkdir -p "${EXPORT_FAILURES_DIR}"
@@ -16,29 +16,16 @@ mkdir -p "${EXPORT_FAILURES_DIR_TMP}/xml_logs"
 #Delete the exsisting logs
 rm -rf /opt/pg/log/*
 cd ~/work/pg_ui/devtools
-test_tag=uilocal
-export AURORA=1
 
 # Need to add a couple dirs to python path to run the tests
 sed -ri "s/import re$/import re\nsys\.path\.insert\(0, '\/opt\/pg')/" ~/work/pg_ui/guitest/gui/test_gui.py
 sed -ri "s/sys\.path\.insert\(0, '\/opt\/pg'.*/sys\.path\.insert\(0, '\/opt\/pg')\n\sys\.path\.insert\(0, '\/opt\/pg\/systest\/guitest')/" ~/work/pg_ui/guitest/gui/test_gui.py
 
 #Exporting pipeline variables
-if [[ "${PIPELINE}" == "pgui-smoke" ]]; then
-  export BUILD_GUI=1
-  export EXCLUDE_NON_GUI=1
-  export EXCLUDE_UNSTABLE=1
-elif [[ "${PIPELINE}" == "pgui-extended" ]]; then
-  export BUILD_GUI=1
-  export EXCLUDE_NON_GUI=1
-  export BUILD_NIGHTLY=1
-  export EXCLUDE_NON_NIGHTLY=1
-  export EXCLUDE_UNSTABLE=1
-else
+if [[ "${PIPELINE}" != "pgui-smoke" && "${PIPELINE}" != "pgui-extended" ]]; then
   echo "UNKOWN PIPELINE:  ${PIPELINE}"
+  exit 1
 fi
-
-BUILD_ID=
 
 # Disable ipv6
 echo 1 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
@@ -54,36 +41,36 @@ sleep 0.2
 pgrep rsyslogd >> /dev/null  || $(sudo rsyslogd &)
 
 # Use grunt to figure out the number of tests
-tests_count_output=`grunt e2etest --pipes=10 --pipe=$instance_no --count`
+tests_count_output=`grunt e2etest --pipes=10 --pipe=${instance_no} --count`
 # Taking out the number from the whole message
 tests_count=$( echo ${tests_count_output/Done, without errors.} | cut -f 1 -d " " )
 
-echo "No. of tests will be run: $tests_count"
-for test_no in $(seq 1 "$tests_count"); do
+echo "No. of tests will be run: ${tests_count}"
+for test_no in $(seq 1 "${tests_count}"); do
   # Use grunt to figure out the name of test
-  test_name=`grunt e2etest --pipes=10 --pipe=$instance_no --index=$test_no --name`
+  test_name=`grunt e2etest --pipes=10 --pipe=${instance_no} --index=${test_no} --name`
   # take the name out of the output
   test_name=$( echo ${test_name/Done, without errors.} | sed 's/.*--test_pattern=\(.*\)\( .*\)/\1/' | cut -f 1 -d " " )
-  echo "Running test: ====== $test_name ========="
+  echo "Running test: ====== ${test_name} ========="
 
   # Run the test and capture it's output
   grunt e2etest --pipes=10 --pipe=${instance_no} --index=${test_no} >& "${EXPORT_FAILURES_DIR}/${test_name}.log"
   result="$?"
 
-  if [[ "$result" -ne "0" ]] ; then
+  if [[ "${result}" -ne "0" ]] ; then
     echo "                 FAILED"
-    mv "$EXPORT_FAILURES_DIR/${test_name}.log" "$EXPORT_FAILURES_DIR_TMP/${test_name}.FAILED.log"
+    mv "${EXPORT_FAILURES_DIR}/${test_name}.log" "${EXPORT_FAILURES_DIR_TMP}/${test_name}.FAILED.log"
     # grunt generated logs are generated in /opt/pg/log/ and aren't in tar.gz form
-    tar -zcf "$EXPORT_FAILURES_DIR_TMP/${test_name}.tar.gz" /opt/pg/log/${test_name}*
+    tar -zcf "${EXPORT_FAILURES_DIR_TMP}/${test_name}.tar.gz" /opt/pg/log/${test_name}*
   else
-    mv "$EXPORT_FAILURES_DIR/${test_name}.log" "$EXPORT_FAILURES_DIR_TMP/${test_name}.log"
+    mv "${EXPORT_FAILURES_DIR}/${test_name}.log" "${EXPORT_FAILURES_DIR_TMP}/${test_name}.log"
   fi
   rm -rf /opt/pg/log/*
-  rm -rf $EXPORT_FAILURES_DIR/*
+  rm -rf ${EXPORT_FAILURES_DIR}/*
 done
 # run tests for this instances
 
-echo "$tests_count" > $EXPORT_FAILURES_DIR_TMP/total_tests_inst${instance_no}
+echo "${tests_count}" > ${EXPORT_FAILURES_DIR_TMP}/total_tests_inst${instance_no}
 #Copy logs to /opt/pg/log for get_latest_logs to copy the tests.
 mkdir -p /opt/pg/log/grunt-pipe-${instance_no}
 cp -r ${EXPORT_FAILURES_DIR_TMP} /opt/pg/log/
